### PR TITLE
Initial pre-defined types

### PR DESCRIPTION
**Pull request by Libbum**
WIP for #365.

Types and docstrings added, but have not filtered them through examples or anything. No tests done yet, but the results do work out as the docstrings suggest.

### CODE REVIEW

**Comment by Datseris** [comment]
ah you did it already. okay I'll review tonight

**Comment by Datseris** [comment]
my suggestion is that agent abstract types go to a new file in the `core` folder: `agents.jl`

**Comment by Libbum** [comment]
At the moment this generates `<: AbstractAgent`s only. If we want to dispatch on `<: GraphAgent` then we'll need to create subtypes of AbstractAgent for each space, then modify structs and the macro accordingly. From your comment on the other thread, this may not be that important though...

**Comment by Datseris** [comment]
I've done some doc updates and this is good to go from my end. Let's only add one basic test to be on the clear side regarding codecov.

**Comment by Libbum** [comment]
I was going to also update some / all examples to use the macro - does that makes sense to you too?

Looks like you've made `vel` a mandatory variable in the `ContinuousSpace`. We only have it as [optional](https://github.com/JuliaDynamics/Agents.jl/blob/5df08e22d10d5fc4721760b66a12a0cd12ac69ed/src/core/model.jl#L277) in the `agent_validator` however. Should I promote it to mandatory there?

**Comment by Datseris** [comment]
Sorry, forgot to mention the velocity change I did. Yes I made that because since it is anyway automated, we might as well add it for convenience. No reason to add it to the validator though, it is still not mandatory.

**Comment by Datseris** [comment]
> I was going to also update some / all examples to use the macro - does that makes sense to you too?

I'm not sure about this. I was thinking that we'd leave the examples as-is for clarity. Macros tend to be unclear unless you really know what they do. But on the other hand, it is worth it to change some of the examples? Because this new interface is more convenient? Not sure! I'd say we leave it for now, its a really recent change after all.

**Comment by Libbum** [comment]
I saw you added a discussion in Schelling. I think this enough for now, we'll see how people use it. I'll add a changelog entry and merge this then.

**Pull request merged**
