### PR TITLE
Set default value of `r` to `r=1` for `randomwalk!`

### PR DESCRIPTION
**Pull request by MA-Ramirez**
Pull request regarding issue #754

### CODE REVIEW

**Review by Datseris — CHANGES_REQUESTED** [review]
Thanks, but have a look at the continuous code a bit closer. You will see that for continuous space the implementation is different. If `r` is not given, the velocity is used instead. Not `1`. So, this PR should not change the continuous space version.

**Review by Datseris — APPROVED** [review]

**Comment by Tortar** [comment]
the types should be kept, otherwise this can cause performance issues, I added them

**Comment by Datseris** [comment]
adding this type decleration does not affect perforamance. Julia will anyways compile a dedicated version for each input type whether it is declared or not. The only thing this does is throw a method error if someone tried to use the function with a non-real input argument, which I guess is useful.

**Comment by Tortar** [comment]
ops @Datseris, at least there is the motivation you mentioned :-)

**Review by Tortar — APPROVED** [review]

**Pull request merged**
