### PR TITLE
Solve caching problems in offsets_within_radius

### PR DESCRIPTION
**Pull request by Tortar**
This would solve #750, but it's still a bit clumsy, to improve the design we should change the keys type of `offsets_within_radius` from `float64` to `int` and accept an `int` instead of a `real` in `calculate_offsets`, is this fine?

### CODE REVIEW

**Comment by Tortar** [comment]
something is failing with the latest commit, will look into that soon

**Comment by Tortar** [comment]
something is failing with the latest commit, will look into that soon

**Comment by Tortar** [comment]
something is failing with the latest commit, will look into that soon

**Comment by Tortar** [comment]
ok, the problem is related to the previous ceiling with the `euclidean` metrics when the radius is not an integer for grid spaces (there are no problems anymore with continuous spaces since the ceiling is accounted for before calling these functions), so what to do about that? probably it's breaking to change this but I think that ceiling and flooring with different metrics would be a surprise for the user, so it would probably be an unexpected behaviour which is something we should avoid, what do you think @Datseris ?

**Comment by Datseris** [comment]
Well, the problem is we need the Euclidean type metric for the continuous space. For grid space in my opinion it is nonsense to use euclidean metric anyways. But for continuous space it makes sense to have the boxes according to this euclidean metric...

What is currently happening with the boxes in the continuous space? You are still rouding the radious always to an integer multiple of the underlying compartment size, right? Doesn't this change the accuracy of the algorithm, i.e., make it less accurate? 

There is a plotting code in the continuous space test file that you can use to visualize your change.

**Comment by Tortar** [comment]
I don't think there should be any change in the behaviour of continuous space, these lines in continuous.jl are untouched in this pr

```julia
    # Ceiling since the grid has euclidean metric (but probably I could write that ceiling instead of flooring is better for accuracy of `nearby_ids` instead of the current comment)
    grid_r = ceil(Int, (r + δ) / model.space.spacing)
```

or am I missing something?

**Comment by Tortar** [comment]
This is I think the final version, unfortunately I have some problems running GLMakie so as a final verification I would test the changes gathering some statistics of the flocking model before and after this PR, so that to see if all is still the same (which I think it is) :-)

**Comment by Tortar** [comment]
ok, everything works as expected, running

<details> <summary> Flocking model with statistics </summary> 
```julia
using Agents, LinearAlgebra, Random

@agent Bird ContinuousAgent{2} begin
    speed::Float64
    cohere_factor::Float64
    separation::Float64
    separate_factor::Float64
    match_factor::Float64
    visual_distance::Float64
end


function flocking(;
    n_birds = 100,
    speed = 1.0,
    cohere_factor = 0.25,
    separation = 4.0,
    separate_factor = 0.25,
    match_factor = 0.01,
    visual_distance = 5.0,
    extent = (100, 100),
    spacing = visual_distance / 1.5,
    rng = rng
)
    space2d = ContinuousSpace(extent; spacing)
    model = StandardABM(Bird, space2d, scheduler = Schedulers.Randomly(), rng=rng)
    for _ in 1:n_birds
        vel = Tuple(rand(model.rng, 2) * 2 .- 1)
        add_agent!(
            model,
            vel,
            speed,
            cohere_factor,
            separation,
            separate_factor,
            match_factor,
            visual_distance,
        )
    end
    return model
end

function agent_step!(bird, model)
    neighbor_ids = nearby_ids(bird, model, bird.visual_distance)
    N = 0
    match = separate = cohere = (0.0, 0.0)
    for id in neighbor_ids
        N += 1
        neighbor = model[id].pos
        heading = neighbor .- bird.pos
        cohere = cohere .+ heading
        if euclidean_distance(bird.pos, neighbor, model) < bird.separation
            separate = separate .- heading
        end
        match = match .+ model[id].vel
    end
    N = max(N, 1)
    cohere = cohere ./ N .* bird.cohere_factor
    separate = separate ./ N .* bird.separate_factor
    match = match ./ N .* bird.match_factor
    bird.vel = (bird.vel .+ cohere .+ separate .+ match) ./ 2
    bird.vel = bird.vel ./ norm(bird.vel)
    move_agent!(bird, model, bird.speed)
end

rngs = [MersenneTwister(x) for x in 1:10]

for rng in rngs
    model = flocking(rng = rng)
    step!(model, agent_step!, 200)
    print(sum(map(a -> a.vel[1], collect(values(model.agents)))), " ")
    print(sum(map(a -> a.vel[2], collect(values(model.agents)))), "\n")
end
```
</details>

where I ran 10 flocking models each with a different rngs always return before and after this PR the same output, which is 

```julia
2.2525640873792314 16.08840559085231
-8.669039492814019 2.026938937148426
0.5832006320775777 9.126733961314178
-2.1906408823711 16.068520361089284
-17.656967292641074 -6.6928148110441645
-0.07816622407620577 4.751271031761771
-2.6621811314673165 -8.995219690701814
3.796578622360355 6.4012949051749
-5.479452157044974 3.427887346049989
6.671483265577846 -7.2814175590563535
```

**Comment by Tortar** [comment]
Also simplified the `calculate_offsets` function which is now even faster with euclidean and manhattan metrics: e.g. for radius 1 it is 1.5 faster and radius 5 it is 4 times faster

**Review by Datseris — APPROVED** [review]
oof I finally udnerstand this PR. tjanks a lot for the effort! can yoi please add a changelog entry and then go ahead and merge?

**Comment by Datseris** [comment]
haha it's amazing how badly i type when i type fast :D

**Comment by Tortar** [comment]
I can't even type fast :D

**Pull request merged**
