### PR TITLE
fix: index properly into multi-type propensities

### LINKED ISSUE #1071: `add_event!` does not use correct propensities in multi-agent simulation
**Describe the bug**
`add_event!` does not use correct propensities in multi-agent simulation. It is due to improper indexing of `model.propensities_each_type`.

**Minimal Working Example**
Run the following code:
```
using Agents
using Random: Xoshiro

@agent struct Pathogen(NoSpaceAgent)
	genotype::Vector{Int64}
end
@agent struct Host(NoSpaceAgent)
	genotype::Vector{Int64}
end
@multiagent ImmuneAgent(Host, Pathogen)

function nhosts(model)
	model.N
	#count(x -> variantof(x) == Host, allagents(model))
end

function growth!(agent, model)
	model.N +=1
	replicate!(agent, model)
end
function logistic_death!(agent, model)
	model.N -=1
	remove_agent!(agent, model)
end
function viral_deactivation!(agent, model)
	remove_agent!(agent, model)
end
function logistic_growth_propensity(agent, model)
	return model.r
end
function logistic_death_propensity(agent, model)
	N = model.N
	r = model.r
	K = model.K

	prob = r*N/K
	return prob
end
function viral_deactivation_propensity(agent, model)
	return model.d
end
growth_event = AgentEvent(
	action! = growth!, propensity = logistic_growth_propensity,
	types = Host
)
death_event = AgentEvent(
	action! = logistic_death!, propensity = logistic_death_propensity,
	types = Host
)
deactivation_event = AgentEvent(
	action! = viral_deactivation!, propensity = viral_deactivation_propensity,
	types = Pathogen
)

const genome = 1:10

function initialize_model(n_hosts, n_pathogens)
	properties = Dict(
		:r => 1,
		:K => 100,
		:N => n_hosts,
		:d => 0.5
	)
	events = (growth_event, death_event, deactivation_event)
	m = EventQueueABM(
		ImmuneAgent, events, nothing; properties, warn = false
	)
	agents = let
		rng = abmrng(m)
		for _ in 1:n_hosts
			h = ImmuneAgent(Host(m; genotype = rand(rng, genome, 3)))
			add_agent!(h, m)
		end

		for _ in 1:n_pathogens
			p = ImmuneAgent(Pathogen(m; genotype = rand(rng, genome, 3)))
			add_agent!(p, m)
		end
		allagents(m)
	end
	m
end

properties = Dict(
  :r => 1,
  :K => 100,
  :N => 1,
  :d => 1
)
events = (growth_event, death_event, deactivation_event)
m = EventQueueABM(
  ImmuneAgent, events, nothing; properties, warn = false, rng = Xoshiro(1234)
)
rng = abmrng(m)

p = ImmuneAgent(Pathogen(m; genotype = rand(rng, genome, 3)))
add_agent!(p, m)

h = ImmuneAgent(Host(m; genotype = rand(rng, genome, 3)))
add_agent!(h, m)
abmqueue(m)
```
yields the stacktrace
```
ERROR: LoadError: BoundsError: attempt to access 1-element Vector{Float64} at index [3]
Stacktrace:
 [1] getindex
   @ ./essentials.jl:13 [inlined]
 [2] add_event!(agent::ImmuneAgent, model::EventQueueABM{…})
   @ Agents ~/src/Agents.jl/src/core/model_event_queue.jl:261
 [3] extra_actions_after_add!
   @ ~/src/Agents.jl/src/core/model_event_queue.jl:228 [inlined]
 [4] add_agent_to_model!
   @ ~/src/Agents.jl/src/core/model_accessing_API.jl:19 [inlined]
 [5] add_agent_own_pos!
   @ ~/src/Agents.jl/src/core/space_interaction_API.jl:200 [inlined]
 [6] add_agent!(agent::ImmuneAgent, model::EventQueueABM{…})
   @ Agents ~/src/Agents.jl/src/spaces/nothing.jl:21
 [7] top-level scope
   @ ~/src/Agents.jl/examples/hostpathogen.jl:97
 [8] include(fname::String)
   @ Base.MainInclude ./client.jl:489
 [9] top-level scope
   @ REPL[2]:1
in expression starting at /Users/jesselin/src/Agents.jl/examples/hostpathogen.jl:97
Some type information was truncated. Use `show(err)` to see complete types.
```

**Agents.jl version**

6.1.4

### PR DESCRIPTION
**Pull request by jesseylin**
Fixes #1071

### CODE REVIEW

**Comment by Tortar** [comment]
thanks a lot for the help! But I'm a bit confused on why it works and I'm a bit short on time to investigate it further currently. At the same time, I would like to ask: would it be possible to "move" the fix to the construction of the EventQueueABM so that we don't need to spend time at each event addition?

**Comment by jesseylin** [comment]
Yes fixing some of the methods in `EventQueueABM` would be the preferred way to fix it. I will look into it later this week.

**Comment by Tortar** [comment]
I pushed a commit, I think this should be the more correct fix, let me know if you find it right :-)

**Review by Tortar — APPROVED** [review]

**Comment by jesseylin** [comment]
Thanks, this seems much better I agree.

**Comment by Tortar** [comment]
I will release a new version with the fix soon

**Pull request merged**
