### PR TITLE
Improve performance of EventQueueABM by better union splitting

### PR DESCRIPTION
**Pull request by Tortar**
before

```julia
julia> model = initialize_rps();

julia> @benchmark step!($model)
BenchmarkTools.Trial: 10000 samples with 197 evaluations.
 Range (min … max):  426.081 ns …  56.132 μs  ┊ GC (min … max): 0.00% … 98.59%
 Time  (median):     471.038 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   512.019 ns ± 745.854 ns  ┊ GC (mean ± σ):  5.40% ±  4.60%

         ▂▄▆▇█▇▆▄▃▁                                              
  ▁▁▂▃▄▅████████████▆▅▃▃▃▂▂▂▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁ ▃
  426 ns           Histogram: frequency by time          641 ns <

 Memory estimate: 378 bytes, allocs estimate: 7.
```

after

```julia
julia> model = initialize_rps();

julia> @benchmark step!($model)
BenchmarkTools.Trial: 10000 samples with 207 evaluations.
 Range (min … max):  343.237 ns …  46.423 μs  ┊ GC (min … max): 0.00% … 98.19%
 Time  (median):     390.423 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   409.583 ns ± 565.531 ns  ┊ GC (mean ± σ):  3.01% ±  2.53%

              ▂▃▅████▇▅▄▂▁                                       
  ▁▁▁▁▁▂▂▃▄▅▇█████████████▇▆▅▅▄▄▄▃▃▄▄▄▃▃▃▃▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁ ▃
  343 ns           Histogram: frequency by time          495 ns <

 Memory estimate: 157 bytes, allocs estimate: 2.
```

### CODE REVIEW

**Comment by Datseris** [comment]
that's big!

can you give more info here? What are you doing? What is "union splitting" in this context?

**Comment by Tortar** [comment]
The key idea here in my opinion is understanding that tuples are not made for this task (at least currently) because when the access to a tuple is random and there are multiple types inside it, the tuple will not union split but just use a dynamic dispatch mechanism. When the access is fixed a tuple would be instead be better. A SizedVector is instead a good one because as a Vector it will union-split, at the same time we know the size of it, so we can use a fixed-size one.

**Comment by Datseris** [comment]
What does "union-split" mean?

**Review by Datseris — APPROVED** [review]

**Comment by Tortar** [comment]
https://julialang.org/blog/2018/08/union-splitting/

**Pull request merged**
