### PR TITLE
Handle compatibility with dev version of AgentsExampleZoo better

### PR DESCRIPTION
**Pull request by Tortar**
Since #875 has some problems I do this separately, see https://github.com/JuliaDynamics/Agents.jl/pull/875#issuecomment-1891054174 for why we need this

edit: actually #875 is fine because also #946 has the same errors, but both work locally. However, let's merge this separately anyway since it is more sensible anyway

### CODE REVIEW

**Comment by Tortar** [comment]
Strangely enough this works instead, github is crazy :S

**Comment by Datseris** [comment]
The existence of this PR highlights why one should avoid circular dependencies in packages.

**Comment by Tortar** [comment]
I think that it actually higlights this when both packages depends on *unreleased versions*. We are in this strange situation because of this. When both packages will be released, there will be no problem like this anymore, it will be as if the models where inside Agents.jl. We will just pin the major version on both packages to ensure everything works. 

I think the only problem which could arise is that if we make a major version of Agents without updating AgentsExampleZoo he will need a downgrade of Agents. But this will never happen if we don't completely forget about AgentsExampleZoo :D

**Comment by Datseris** [comment]
> I think that it actually higlights this when both packages depends on _unreleased versions_.

The same problem will also always happen for every major version change in either package.

**Comment by Datseris** [comment]
In any case, let's just get this in for now and we can consider more how to deal with it before releasing v6.

**Review by Datseris — APPROVED** [review]

**Pull request merged**
