### PR TITLE
Fix reset button in abmexploration

### LINKED ISSUE #944: Fix reset button working in `abmexploration`
#942 broke that since when the model is reset the time returns to 0 as it should, but this means that the data graphs should take into account this new behavior to function properly

### PR DESCRIPTION
**Pull request by Tortar**
Fixes #944

### CODE REVIEW

**Review by Datseris — COMMENTED** [review]
Can you please describe the PR? What's the purpose of the offset time?

**Comment by Tortar** [comment]
It helps to track the shifting amount for new data points appearing when plotting the agent/model data, otherwise the new points would cover the old ones in the plots

**Review by Datseris — CHANGES_REQUESTED** [review]
Something is wrong with git here. I see all commits of the PR #964 here as well.

**Comment by Tortar** [comment]
Tested the branch at the latest commit locally, everything works, I think github is not working properly as usual, but let's see if everything works after merging

**Review by Datseris — APPROVED** [review]

**Pull request merged**
