### PR TITLE
Support keyword arguments for add_agent!

### PR DESCRIPTION
**Pull request by itsdfish**
When a struct has many fields, it can be helpful to pass NamedTuples to constructors rather than positional arguments. I added some of this functionality to `add_agents!`, along with a simple test. Since I am not very familiar with the code, please take a moment to review.  

Note that the test errors are preexisting. 

Thanks!

### CODE REVIEW

**Comment by Datseris** [comment]
Good idea!

- The docstring must be updated to reflect this change.
- Changelog must be updated
- The conflicts must be resolved appropriately

**Comment by Datseris** [comment]
@itsdfish I will do a proper review, but this can only be done when no conflicts exist.

**Comment by itsdfish** [comment]
I updated the docs and change log. I also tried to deconflict the pull request. Edits are allowed from maintainers. Please feel to make any necessary edits if convenient to do so.

**Comment by Datseris** [comment]
God f*cking damn it git. I didn't want to merge this.

**Comment by Datseris** [comment]
@itsdfish please re-open a Pull Request from your `master` to Agents.jl `master`. I've reverted the marge...

**Pull request merged**
