### PR TITLE
Api additions

### LINKED ISSUE #60: Some things should be more convenient
At the moment the public API has some rough edges, expecting the user to do operations that I think should be quite simple to support generically. I am writing some examples here, but please feel free to edit this comment to add more.

# Adding agents
from the forest fire:
```julia
p = rand()
      if p ≤ forest.properties[:p]
        bigest_id = maximum(keys(forest.agents))
        treeid = bigest_id +1
        tree = Tree(treeid, (1,1), true)
        add_agent!(tree, node, forest)
      end
```
it seems that to add a new Agent the user should always try to find the `biggest_id` and add one. But in these 4 lines of code, what I want to do is just add one "alive" agent at the `node`. This should require only one line of code, not 4.

# Iterating through the nodes of the space
from forest fire:
```julia
 shuffled_nodes = Random.shuffle(1:gridsize(forest))
  for node in shuffled_nodes  # randomly go through the cells and
```
I don't think the user should do the first line, and should definitely not have to use the undocumented function `gridsize`. I think we should have some high level functions that iterate through nodes:

1. Randomly
2. Sequentially (by node ID)
3. By population; sort the nodes by the amount of agents they have, having the most populated first (this could be very useful for social models on arbitrary graphs)

# Empty nodes
We should define `isempty(node, model)` that returns internally checks `length(model.space.agent_positions[node]) == 0 `.

In general I do not find it great design if a user has to access a field of a field of a field and check if it is empty.

# Reexport `nv`, `ne` or define somefunctions that do that
It is useful to know how many grid points there are. and in the end of the day they are displayed when the model is printed. We should re-export `nv`, `ne` from LightGraphs.

### PR DESCRIPTION
**Pull request by Datseris**
Closes #60

At the moment the part about iterating over nodes is not yet addressed.

@kavir1698 I have noticed that we have to define some functions that do convert a node or position to the agent's position type. Because if you see my implementation on add_agent! it currently only works for Integer positions.

Next week I'll be travelling, so feel free to contribute to this PR.

### CODE REVIEW

**Comment by kavir1698** [comment]
> Because if you see my implementation on add_agent! it currently only works for Integer positions.

`function add_agent!(node, model::ABM, properties...)...` should work for both integers and tuples.

**Comment by Datseris** [comment]
> should work for both integers and tuples

yeap, this is exactly what I am saying as well. We should do it, but I am in between travels right now, so I won't have time to continue here for a couple of weeks.

**Comment by kavir1698** [comment]
What I mean is that this function already works because `add_agent!(agent, node, model)` works for both integers and tuples.

**Comment by Datseris** [comment]
I am removing AgentPlots from docs, so that we can release 2.0 at some point soon. Then, we can release AgentPlots and add it to the documentation.

So I think for this to close we need the following:

1. Add iteration over nodes, as discussed in #60 
2. Add unit tests for the new functions that are implemented in this PR

I think this is the only thing that is holding 2.0

**Comment by Datseris** [comment]
@kavir1698 `combine_columns!` doesn't work. I can't build the docs because :
```
using Statistics
combine_columns!(data, "mood_sum", [mean])
data[!, end]
```
gives
```

julia> combine_columns!(data, "mood_sum", [mean])
ERROR: MethodError: reduce_empty(::typeof(Base.add_sum), ::Type{Union{}}) is ambiguous. Candidates:
  reduce_empty(::typeof(Base.add_sum), ::Type{T}) where T<:Union{UInt16, UInt32, UInt8} in Base at reduce.jl:240
  reduce_empty(::typeof(Base.add_sum), ::Type{T}) where T<:Union{Int16, Int32, Int8} in Base at reduce.jl:239
Possible fix, define
  reduce_empty(::typeof(Base.add_sum), ::Type{Union{}})
Stacktrace:
 [1] mapreduce_empty(::typeof(identity), ::Function, ::Type) at .\reduce.jl:255
 [2] _mapreduce(::typeof(identity), ::typeof(Base.add_sum), ::IndexLinear, ::Array{Union{},1})
at .\reduce.jl:309
 [3] _mapreduce_dim(::Function, ::Function, ::NamedTuple{(),Tuple{}}, ::Array{Union{},1}, ::Colon) at .\reducedim.jl:312
 [4] #mapreduce#555 at .\reducedim.jl:307 [inlined]
 [5] mapreduce(::Function, ::Function, ::Array{Union{},1}) at .\reducedim.jl:307
 [6] _sum(::Function, ::Array{Union{},1}, ::Colon) at .\reducedim.jl:657
 [7] _sum(::Array{Union{},1}, ::Colon) at .\reducedim.jl:656
 [8] #sum#558 at .\reducedim.jl:652 [inlined]
 [9] sum at .\reducedim.jl:652 [inlined]
 [10] _mean(::Array{Union{},1}, ::Colon) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\Statistics\src\Statistics.jl:135
 [11] #mean#1(::Function, ::typeof(mean), ::Array{Union{},1}) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\Statistics\src\Statistics.jl:132 [12] mean(::Array{Union{},1}) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\Statistics\src\Statistics.jl:132
 [13] (::getfield(Agents, Symbol("##50#52")){Array{Symbol,1},typeof(mean)})(::NamedTuple{(),Tuple{}}) at C:\Users\datseris\.julia\dev\Agents\src\simulations\data_collector.jl:137
 [14] do_call(::getfield(Agents, Symbol("##50#52")){Array{Symbol,1},typeof(mean)}, ::GroupedDataFrame{DataFrame}, ::NamedTuple{(),Tuple{}}, ::Int64) at C:\Users\datseris\.julia\packages\DataFrames\yH0f6\src\groupeddataframe\grouping.jl:469
 [15] _combine(::Pair{Array{Symbol,1},getfield(Agents, Symbol("##50#52")){Array{Symbol,1},typeof(mean)}}, ::GroupedDataFrame{DataFrame}) at C:\Users\datseris\.julia\packages\DataFrames\yH0f6\src\groupeddataframe\grouping.jl:740
 [16] combine(::Pair{Array{Symbol,1},getfield(Agents, Symbol("##50#52")){Array{Symbol,1},typeof(mean)}}, ::GroupedDataFrame{DataFrame}) at C:\Users\datseris\.julia\packages\DataFrames\yH0f6\src\groupeddataframe\grouping.jl:437
 [17] #by#200 at C:\Users\datseris\.julia\packages\DataFrames\yH0f6\src\groupeddataframe\grouping.jl:1071 [inlined]
 [18] by at C:\Users\datseris\.julia\packages\DataFrames\yH0f6\src\groupeddataframe\grouping.jl:1071 [inlined]
 [19] combine_columns!(::DataFrame, ::Array{Symbol,1}, ::Array{typeof(mean),1}) at C:\Users\datseris\.julia\dev\Agents\src\simulations\data_collector.jl:137
 [20] combine_columns!(::DataFrame, ::String, ::Array{typeof(mean),1}) at C:\Users\datseris\.julia\dev\Agents\src\simulations\data_collector.jl:153
 [21] top-level scope at none:0
```

Can you please fix it on this PR?

**Comment by Datseris** [comment]
I have commented out the Examples and Mesa pages. ALl of them are outdated. I will update forest fire soon though, but only after we merge this.

**Comment by Datseris** [comment]
found the problem I fix it in the next pr

**Comment by kavir1698** [comment]
The `combine_columns!` works fine. We just had to change the column names after we had updated the code. The following line works.

```jl
combine_columns!(data, "sum(mood)", [mean])
````

**Comment by kavir1698** [comment]
> I will update forest fire soon though

I have updated the example file already. The documentation needs an update.

**Comment by kavir1698** [comment]
I still think `add_agent!(node::Integer, model::ABM, properties...)` method needs to be fixed. It only works with a certain order of agent fields

**Comment by Datseris** [comment]
Please open an issue for this then, and maybe even provide a MWE that shows the problem?

**Pull request merged**
