### PR TITLE
social distancing example

### PR DESCRIPTION
**Pull request by kavir1698**

### CODE REVIEW

**Comment by Datseris** [comment]
I think we should merge the continuous space example and the social distancing example. They are too much similar, and so far the examples in the docs do a good job of being diverse and each example showcasing a unique scenario so to speak.

**Comment by Datseris** [comment]
We can have one nice example that is "introduction" to continuous space. Starts with balls just jumping off each other, then adds virus transmission, then adds social distancing (i.e. makes some balls fixed).

**Comment by kavir1698** [comment]
Good idea. I will merge the two examples.

**Comment by Datseris** [comment]
Note to self: Once this is updated to use #170 , I want to add a note for people to understand that Agents.jl is _not_ a billiards simulator, and all this ball scattering is highly inaccurate, and should use DynamicalBilliards.jl or HardSphereDynamics.jl for more rigorous stuff.

**Comment by Datseris** [comment]
HELL YEAH!!!

socialdist5

**Comment by Datseris** [comment]
https://juliadynamics.github.io/Agents.jl/previews/PR162

**Comment by Datseris** [comment]
@Libbum have a look at `plotabm` function. This is the way to plot abms in continous space in my opinion, (from the API perspective). It seems natural to use this function to plot this nice model you have shown us with the houses etc. 

(`plotabm` is in AgentsPLots.jl)

**Comment by Libbum** [comment]
Indeed. Frame by frame this works great. 

A discussion for another thread we'll need to have sometime in the near future is how to animate and save data simultaneously.

**Comment by kavir1698** [comment]
Great job, @Datseris !

**Pull request merged**
