### PR TITLE
Documentation update

### PR DESCRIPTION
**Pull request by jarbus**
Created a new PR to keep the revised documentation in a single commit @Datseris.

### CODE REVIEW

**Comment by jarbus** [comment]
Made another change with a force-push to clarify that this case is very rare, still uses one commit.

**Comment by Datseris** [comment]
There is no reason to be concerned about the commit numbers xD I will anyways squash and merge, so the actual PR will be pushed as 1 commit to master no matter how many commits it will have xD

**Comment by jarbus** [comment]
Thanks lol, I'm still pretty new to PRs and thought something like that should be possible but didn't want to assume

**Review by Datseris — CHANGES_REQUESTED** [review]
I'd like two changes:

1) This message should be at the very end of the documentation string. It is certainly not important to be at the very first sentences, which serve to only give a concise description of the function. You can put it after the text regarding the `exact` keyword.

2) We can make the message a bit more precise:
"""
In periodic discrete or continuous spaces, when used with a radius larger than half of the entire space, this function may find the same agent(s) more than once.
See Issue #566 online for more information.
"""

**Pull request merged**
