### PR TITLE
periodicity in continuous space

### PR DESCRIPTION
**Pull request by Datseris**
Adds periodicity for continuous space

### CODE REVIEW

**Comment by Datseris** [comment]
@kavir1698 I am a bit confused with this database. at the moment `move_agent!` doesn't do anything to the database. How does the database knows that the agent has been moved?

**Comment by kavir1698** [comment]
@Datseris Yeah, let me try to understand what is happening.

**Comment by kavir1698** [comment]
Ok. The database doesn't get updated, but agent objects do. And the plotting function in the example uses agent objects, not the database.

**Comment by Datseris** [comment]
Okay but then we have to fix this right? Because when calling `space_neighbors`, this checks the database. So after each agent is moved the database has to be updated for it to be correct?

**Comment by kavir1698** [comment]
Yes, correct. I'll take care of that. We will need another statement for updating the database.

**Pull request merged**
