### PR TITLE
Update abstract.jl solves #1045

### PR DESCRIPTION
**Pull request by amynang**
The culprit behind #1045 was the use of poly! for user defined polygons. As a first step, I replaced it with  `scatter!(p, p.pos; p.color, p.marker, p.markersize, p.agentsplotkwargs...)` and generating the plot with the custom polygon worked. In that case I think the whole if else statement is no longer necessary so I removed it.

```
if user_used_polygons(p.agent_marker[], p.marker[])
poly!(p, p.marker; p.color, p.marker, p.markersize, p.agentsplotkwargs...)
else
scatter!(p, p.pos; p.color, p.marker, p.markersize, p.agentsplotkwargs...)
end
```

### CODE REVIEW

**Comment by Tortar** [comment]
I didn't test anything but I feel like removing `poly!` shouldn't be the solution, what does the error say when you try to create the video with the previous code?

**Comment by Tortar** [comment]
ah also, thanks for your help on this :-)

**Comment by Datseris** [comment]
unfortunately i have to agree, removing `poly!` also doesn't sound like a solution to me. Does the `scatter!` actually plot the polygons..? Does the flocking video looks like flocking, with triangles moving and rotating around? If not, then we haven't solved the problem.

I suspect that this code needs to stay as is, with `if`:
```julia
if user_used_polygons(p.agent_marker[], p.marker[])
poly!(p, p.marker; p.color, p.marker, p.markersize, p.agentsplotkwargs...)
else
scatter!(p, p.pos; p.color, p.marker, p.markersize, p.agentsplotkwargs...)
end
```
but what needs to be done is that we cannot blindly propagate `p.agentsplotkwargs` anymore. There are some keywords that `poly!` doesn't accept that are otherwise valid for `scatter!`, so we have to filter them out.

**Comment by amynang** [comment]
@Tortar  [here](https://github.com/user-attachments/files/16238773/error.txt) is the full error message with the original code. [This](https://github.com/amynang/MSB/blob/main/Chapter2/ch2_0_particleworld.jl) is the model where I encountered the problem.

@Datseris scatter! does actually plot the polygons. The first picture is a screenshot with the PR code, the next one is with the agent_marker argument in abmvideo commented out. This is the strange behavior I described earlier, both cases have 100 agents but the first looks zoomed into a part of the space for some reason.
pr1
pr0

**Comment by Datseris** [comment]
> agent_marker argument in abmvideo commented out

Don't do that, it doesn't make sense at the moment. So we don't have to spend resources figuring out what commenting this out does.

I didn't know that `scatter!` plots polygons. Then we can just use `scatter!` for everything. However, let's make sure about one more thing: if you increase the polygon size, for example by multiplying the polygon coordinates with some factor
```julia
const bird_polygon = Makie.Polygon(5 .* Point2f[(-1, -1), (2, 0), (-1, 1)])
function bird_marker(b::Bird)
    φ = atan(b.vel[2], b.vel[1]) #+ π/2 + π
    rotate_polygon(bird_polygon, φ)
end
```

(notice `5 .*`)


Are the polygons larger in size in `scatter!`? Does it respect the actual size of the polygons?

**Comment by amynang** [comment]
Yep, polygons get larger
pr2

**Comment by Tortar** [comment]
I tried your model, and with the last commit I pushed everything works fine, we don't propagate to `poly!` anymore `markersize`, but maybe it never worked? From the code of @datseris it seems so because you define the markersize when creating the polygon

**Review by Tortar — APPROVED** [review]

**Comment by amynang** [comment]
Great! Thanks a lot!

**Review by Datseris — COMMENTED** [review]
Alright, please go into top-level Project.toml and increment the _patch_ version (3rd number) by one. Then we can merge and immediatelly tag a new release.

**Pull request merged**
