### PR TITLE
Patch up models and examples

### PR DESCRIPTION
**Pull request by Libbum**
Recent changes have altered some of the mechanisms we use, that killed off a lot of the functionality in the Models library and broke some examples. This PR fixes that, alongside a few other fixes, like the pre-emptive merge of sugarscape and an omission in the wealth model.

### CODE REVIEW

**Comment by Libbum** [comment]
I'm not sure how this as arisen, any ideas?
We don't seem to be able to do random moves anymore.

```julia
julia> using Agents

julia> model, agent_step!, model_step! = Models.predator_prey()
(AgentBasedModel with 550 agents of type Union{Agents.Models.Grass, Agents.Models.Sheep, Agents.Models.Wolf}
 space: GridSpace with 400 nodes and 1482 edges
 scheduler: by_union, Agents.Models.predator_prey_agent_step!, Agents.dummystep)

julia> step!(model, agent_step!, model_step!, 500)
ERROR: ArgumentError: Sampler for this object is not defined
Stacktrace:
 [1] Random.Sampler(::Type{Random.MersenneTwister}, ::Random.SamplerTrivial{Base.Iterators.Filter{Base.var"#64#65"{Base.Fix2{typeof(isequal),Tuple{Int64,Int64}}},Array{Tuple{Int64,Int64},1}},Tuple{Int64,Int64}}, ::Val{1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Random/src/Random.jl:145
 [2] Random.Sampler(::Random.MersenneTwister, ::Random.SamplerTrivial{Base.Iterators.Filter{Base.var"#64#65"{Base.Fix2{typeof(isequal),Tuple{Int64,Int64}}},Array{Tuple{Int64,Int64},1}},Tuple{Int64,Int64}}, ::Val{1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Random/src/Random.jl:139
 [3] rand(::Random.MersenneTwister, ::Random.SamplerTrivial{Base.Iterators.Filter{Base.var"#64#65"{Base.Fix2{typeof(isequal),Tuple{Int64,Int64}}},Array{Tuple{Int64,Int64},1}},Tuple{Int64,Int64}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Random/src/Random.jl:253 (repeats 2 times)
 [4] rand(::Base.Iterators.Filter{Base.var"#64#65"{Base.Fix2{typeof(isequal),Tuple{Int64,Int64}}},Array{Tuple{Int64,Int64},1}}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Random/src/Random.jl:258
 [5] move!(::Agents.Models.Sheep, ::AgentBasedModel{Union{Agents.Models.Grass, Agents.Models.Sheep, Agents.Models.Wolf},GridSpace{LightGraphs.SimpleGraphs.SimpleGraph{Int64},2,Int64},Agents.var"#by_union#9"{Bool,Bool},Nothing}) at /mnt/turtle/repos/Agents.jl/src/models/predator_prey.jl:128
 [6] predator_prey_agent_step!(::Agents.Models.Sheep, ::AgentBasedModel{Union{Agents.Models.Grass, Agents.Models.Sheep, Agents.Models.Wolf},GridSpace{LightGraphs.SimpleGraphs.SimpleGraph{Int64},2,Int64},Agents.var"#by_union#9"{Bool,Bool},Nothing}) at /mnt/turtle/repos/Agents.jl/src/models/predator_prey.jl:86
 [7] step!(::AgentBasedModel{Union{Agents.Models.Grass, Agents.Models.Sheep, Agents.Models.Wolf},GridSpace{LightGraphs.SimpleGraphs.SimpleGraph{Int64},2,Int64},Agents.var"#by_union#9"{Bool,Bool},Nothing}, ::typeof(Agents.Models.predator_prey_agent_step!), ::typeof(dummystep), ::Int64, ::Bool) at /mnt/turtle/repos/Agents.jl/src/simulations/step.jl:48
 [8] step!(::AgentBasedModel{Union{Agents.Models.Grass, Agents.Models.Sheep, Agents.Models.Wolf},GridSpace{LightGraphs.SimpleGraphs.SimpleGraph{Int64},2,Int64},Agents.var"#by_union#9"{Bool,Bool},Nothing}, ::Function, ::Function, ::Int64) at /mnt/turtle/repos/Agents.jl/src/simulations/step.jl:42
 [9] top-level scope at REPL[6]:1
```

**Comment by Libbum** [comment]
Got It! `node_neighbours` now returns an iterator.

**Comment by Datseris** [comment]
I was holding off of doing this because a lot of the models would need some tweaks with the new space. But since you did it, well okay :D 

feel free to merge this.

**Comment by Libbum** [comment]
I just needed Wolf Sheep to work again. :)

We can re-adjust a second time, no big deal.

**Pull request merged**
