### PR TITLE
Fix Schelling example

### LINKED ISSUE #508: JLD2 integration doesn't work with Documenter builds
The following code, when added to `examples/schelling.jl` doesn't execute correctly during documentation builds. It works when run manually, the only issue is when Documenter runs it.

<details>
  <summary>Code block</summary>
  
```julia
# ## Saving the model state
# It is often useful to save a model after running it, so that multiple branching
# scenarios can be simulated from that point onwards. For example, once most of
# the population is happy, let's see what happens if some more agents occupy the
# empty cells. The new agents could all be of one group, or belong to a third, new, group.
# Simulating this needs multiple copies of the model. `Agents.jl` provides the
# functions [`AgentsIO.save_checkpoint`](@ref) and [`AgentsIO.load_checkpoint`](@ref)
# to save and load models to JLD2 files respectively.

# First, let's create a model with 200 agents and run it for 40 iterations.

model = initialize(numagents = 200, min_to_be_happy = 5, seed = 42)
run!(model, agent_step!, 40)

figure, _ = abm_plot(model; ac = groupcolor, am = groupmarker, as = 10)
figure

# Most of the agents have settled happily. Now, let's save the model.

AgentsIO.save_checkpoint("schelling.jld2", model)

# Note that we can now leave the REPL, and come back later to run the model,
# right from where we left off.

model = AgentsIO.load_checkpoint("schelling.jld2"; scheduler = Schedulers.randomly)

# Since functions are not saved, the scheduler has to be passed while loading
# the model. Let's now verify that we loaded back exactly what we saved.

figure, _ = abm_plot(model; ac = groupcolor, am = groupmarker, as = 10)
figure

# For starters, let's see what happens if we add 100 more agents of group 1

for i in 1:100
    agent = SchellingAgent(nextid(model), (1, 1), false, 1)
    add_agent_single!(agent, model)
end

# Let's see what our model looks like now.

figure, _ = abm_plot(model; ac = groupcolor, am = groupmarker, as = 10)
figure

# And then run it for 40 iterations.

run!(model, agent_step!, 40)

figure, _ = abm_plot(model; ac = groupcolor, am = groupmarker, as = 10)
figure

# It looks like they eventually cluster again. What if the agents are of a new group?
# We can start by loading the model back in from the file, thus resetting the
# changes we made.

model = AgentsIO.load_checkpoint("schelling.jld2"; scheduler = Schedulers.randomly)

for i in 1:100
    agent = SchellingAgent(nextid(model), (1, 1), false, 3)
    add_agent_single!(agent, model)
end

# To visualize the model, we need to redefine `groupcolor` and `groupmarker`
# to handle a third group.

groupcolor(a) = (:blue, :orange, :green)[a.group]
groupmarker(a) = (:circle, :rect, :cross)[a.group]

figure, _ = abm_plot(model; ac = groupcolor, am = groupmarker, as = 10)
figure

# The new agents are scattered randomly, as expected. Now let's run the model.

run!(model, agent_step!, 40)

figure, _ = abm_plot(model; ac = groupcolor, am = groupmarker, as = 10)
figure

# The new agents also form their own clusters, despite being completely scattered.
# It's also interesting to note that there is minimal rearrangement among the existing
# groups. The new agents simply occupy the remaining space.

rm("schelling.jld2")
```
  
</details>

<details>
  <summary>Error message(s) from build log: </summary>

```
┌ Warning: failed to run `@example` block in src/examples/schelling.md:412-414
│ ```@example schelling
│ model = AgentsIO.load_checkpoint("schelling.jld2"; scheduler = Schedulers.randomly)
│ ```
│   c.value =
│    MethodError: Cannot `convert` an object of type JLD2.ReconstructedTypes.var"##Main.__atexample__named__schelling.SchellingAgent#1087" to an object of type AbstractAgent
│    Closest candidates are:
│      convert(::Type{T}, ::T) where T at essentials.jl:205
└ @ Documenter.Expanders ~/.julia/packages/Documenter/Pkhwa/src/Expanders.jl:563
┌ Warning: failed to run `@example` block in src/examples/schelling.md:453-460
│ ```@example schelling
│ model = AgentsIO.load_checkpoint("schelling.jld2"; scheduler = Schedulers.randomly)
│ 
│ for i in 1:100
│     agent = SchellingAgent(nextid(model), (1, 1), false, 3)
│     add_agent_single!(agent, model)
│ end
│ ```
│   c.value =
│    MethodError: Cannot `convert` an object of type JLD2.ReconstructedTypes.var"##Main.__atexample__named__schelling.SchellingAgent#1088" to an object of type AbstractAgent
│    Closest candidates are:
│      convert(::Type{T}, ::T) where T at essentials.jl:205
└ @ Documenter.Expanders ~/.julia/packages/Documenter/Pkhwa/src/Expanders.jl:563
```
</details>

It looks like JLD2 can't see `SchellingAgent` during deserialization, and hence reconstructs a type which isn't compatible with anything else.

### PR DESCRIPTION
**Pull request by AayushSabharwal**
closes #508 
`@eval Main __atexample__named__mockup = $(@__MODULE__) #hide`

Seemed to fix the issue with JLD2 running in Documenter builds in my mockup. Should work here too

### CODE REVIEW

**Review by Libbum — APPROVED** [review]
Assuming the CI passes and things look good in the preview, feel free to merge straight away.

**Comment by Datseris** [comment]
I haven't reviewed any docs yet, so please wait.

**Comment by Datseris** [comment]
kinda off topic, but i want to archive: we have a problem with the axis limits when plotting https://juliadynamics.github.io/Agents.jl/previews/PR509/examples/schelling/#Visualizing-the-data

**Comment by Datseris** [comment]
Suggestions:

- Functions save/load checkpoint should be in the API _before_ the dump to csv. I think they are more likely to be used
- The way keywords are referred in `load_checkpoint` is reduntant. Every sentence starts with "this keyword ...". Instead, Add a subheader `## Keywords` and list the keywords in bullet point.
- The `save_checkpoint` doesn't say that we use JLD2. While it is not necessary for the user to exactly know that we use JLD2, their filename must end in `.jld2`. We need to say this one way or another.
- I suggest that the header of the API section should be `# Save, Load, Checkpoints`

**Comment by AayushSabharwal** [comment]
> filename must end in `.jld2`.

I tested this and turns out it isn't strictly necessary. `save_checkpoint` and `load_checkpoint` work either way. It would only affect `FileIO.save/load` probably. The implementation uses `@save` and `@load` from JLD2.

**Comment by Datseris** [comment]
I don't understand. So if I do `save_checkpoint("file", model)` and then `load_checkpoint("file", model)`, this will work even witout the ending `.jld2`? What if I do `save_checkpoint("file.dat", model)`?

**Comment by AayushSabharwal** [comment]
Yes. It works agnostic of the file extension. For example, I just ran this in the REPL:
```julia
julia> m, _ = Models.hk()
(AgentBasedModel with 100 agents of type HKAgent
 no space
 scheduler: fastest
 properties: ϵ, Agents.Models.hk_agent_step!, Agents.Models.hk_model_step!, Agents.Models.terminate)

julia> AgentsIO.save_checkpoint("file", m)

julia> AgentsIO.load_checkpoint("file")
AgentBasedModel with 100 agents of type HKAgent
 no space
 scheduler: fastest
 properties: ϵ

julia> AgentsIO.save_checkpoint("file.dat", m)

julia> AgentsIO.load_checkpoint("file.dat")
AgentBasedModel with 100 agents of type HKAgent
 no space
 scheduler: fastest
 properties: ϵ
```

**Review by Datseris — APPROVED** [review]

**Comment by AayushSabharwal** [comment]
I noticed the bullets have weird indentation in `load_checkpoint`. I'll fix that, check docs one last time and then push

**Pull request merged**
