### PR TITLE
Fix premade SIR model

### PR DESCRIPTION
**Pull request by fbanning**
`Models.sir()` was broken. I fixed it.

### CODE REVIEW

**Comment by fbanning** [comment]
@Datseris In this PR I fixed the premade SIR model in our package but it's a bit annoying since it requires to use the `Distributions` package for its internal logic. I know that you dislike adding dependencies, so here's the question for you: Are you OK with adding `Distributions` as a direct dependency? 

- If yes, then I can merge this PR as is.
- If not, there are two ways we could tackle this:
  1. Create an extra environment inside the `src/models/` folder that is used by the `Models` module.
  2. Move all the example models from `src/models/` over to AgentsExampleZoo.jl

What do you think?

**Comment by Datseris** [comment]
Why do we need the special distributions? Couldn't we get away with using just `rand` and `randn`? In the end the examples aren't meant to be demonstrating a realistic scientific application scenario, but more like a usage of Agents.jl

**Comment by fbanning** [comment]
I didn't change anything about the model logic, that's just how it always was. Surely I can change the model itself.

**Comment by Datseris** [comment]
I see. I checked the example again, and the dependency tree. Distributions isn't in our dependencies even if you go deeper layers. Additionally, the migration rates are given by the user. Since StatsBase is in our dependencies, couldn't we just use the `sample` function with the migration rates as weights? There is no way to obtain the Poisson distribution, but I'd say we could just use `rate*abs(randn(rng))` instead. 

Are you okay wiwth doing these changes? (You'd also need to do them in the example file.)

**Comment by fbanning** [comment]
OK, things should work

**Comment by Datseris** [comment]
Fantastic! Please increment patch version in Project.toml so I can tag a release immediatelly after!

**Review by Datseris — APPROVED** [review]

**Pull request merged**
