### PR TITLE
Pin Makie to fix Agents 5.17 

### LINKED ISSUE #948: Schelling interactive exploration example ERROR: LoadError: UndefVarError: `MakieLayout` not defined
**Describe the bug**
LoadError: UndefVarError: `MakieLayout` not defined
for Schelling interactive exploration example

**Minimal Working Example**
```jl
"""
https://juliadynamics.github.io/Agents.jl/stable/examples/schelling/

Minimum example of Schelling's exploration example
"""

using Agents

mutable struct Schelling <: AbstractAgent
    id::Int
    pos::NTuple{2,Int}
    group::Int
    mood::Bool
end

function initialize(; N=320, M=20, min_to_be_happy=3)
    # 1. space
    space = GridSpaceSingle((M, M); periodic=false)
    @info "Created gridspace $space"

    # 3. model
    properties = Dict(:min_to_be_happy => min_to_be_happy)
    model = UnremovableABM(Schelling, space; properties)
    @info "Created model $model"

    # add agents
    for n in 1:N
        agent = Schelling(n, (1, 1), n < N / 2 ? 1 : 2, false)
        add_agent_single!(agent, model)
    end
    @info "Added $N agents to the model"
    return model
end

function agent_step!(agent::Schelling, model::AgentBasedModel)
    agent.mood && return

    nearby_same = 0

    for neighbor in nearby_agents(agent, model)
        if agent.group == neighbor.group
            nearby_same += 1
        end
    end

    if nearby_same ≥ model.min_to_be_happy
        agent.mood = true
    else
        move_agent_single!(agent, model)
    end
    return
end

using GLMakie # using a different plotting backend that enables interactive plots
using Statistics: mean

groupcolor(a) = a.group == 1 ? :blue : :orange
groupmarker(a) = a.group == 1 ? :circle : :rect
x(agent) = agent.pos[1]

function explore_model()
    adata = [(:mood, sum), (x, mean)]
    alabels = ["happy", "avg. x"]

    model = initialize(; N=300) # fresh model, noone happy
    parange = Dict(:min_to_be_happy => 0:8)

    figure, abmobs = abmexploration(
        model;
        agent_step!, dummystep, parange,
        ac=groupcolor, am=groupmarker, as=10,
        adata, alabels
    )
    figure
end

explore_model()
```

If the code is **runnable**, it will help us identify the problem faster.

**Agents.jl version**
v5.17.1

### PR DESCRIPTION
**Pull request by Tortar**
Fixes #948 

Fixing the conflict has the effect to merge main into the branch, so it shouldn't be done

(this branch is at the last commit of 5.17.1)

### CODE REVIEW

**Comment by Tortar** [comment]
Releasing a new version from this branch should be enough, but I'm not totally sure about the correct procedure (see https://discourse.julialang.org/t/how-can-i-register-a-new-version-from-a-branch/108730)

**Comment by Datseris** [comment]
The problem is that current `main` has a buttload of changes, and this branch branches of current `main`. Releasing from this branch would not be what you want. Instead, you probably want to find the commit of the 5.17.1 branch from there, add this commit, push to origin, and then go to JuliaHub and tag a release from that branch.

**Comment by Tortar** [comment]
mmmh, this branch is already at the right commit though, so I think it should be okay on that front

**Comment by Datseris** [comment]
right, yes, correct. okay, so then you can go ahead and tag a release from this branch? The PR is not necessary anyways.

**Pull request closed without merging**
