### PR TITLE
Use UnkillableABM for some models in the model folder

### PR DESCRIPTION
**Pull request by Tortar**
Models in this folder aren't still using `UnkillableABM`, but changing this would create conflicts with #766, but they should be really easy to solve anyway. Or we can even wait to change this after #766 is merged.

### CODE REVIEW

**Comment by Tortar** [comment]
ok, I was expecting that all tests would have passed but this is not the case, so this PR is officially a work in progress, probably UnkillableABM doesn't still support all the features a StandardABM supports, so I think this will require a bit of time to work out

**Comment by Datseris** [comment]
this PR unveals another problem: these models are provided purely as convenience. They should not be used in the test suite. Everything in the test suite must create models/agents/stepping functions from scratch.

**Comment by Tortar** [comment]
Now all tests pass, but I think I will try to rewrite the incriminated test suites so that they have the models inside the test file as you suggested :-) I think that we can still use some smaller schelling and flocking models anyway right?

**Comment by Tortar** [comment]
Hopefully this is a better way to test the checkpointed models even if I think some more revisions of tests is still needed :-)

**Pull request merged**
