### PR TITLE
Update to v0.2 of MixedStructTypes

### LINKED ISSUE #967: Syntax check of `@multiagent` is not as correct as it should be:
MWE:

```julia
@multiagent struct MultiSchelling{X}(GridAgent{2})
    @agent struct Civilian # can't re-define existing `Schelling` name
        mood::Bool = false
        group::Int
    end
    @agent struct Governor{X<:Real} # can't redefine existing `Politician` name
        group::Int
        influence::X
    end
end

civ = Civilian(; id = 2, pos = (2, 2), group = 2) # default `mood`

gov = Governor(; id = 3 , pos = (2, 2), group = 2, influence = 0.5)
```

the `gov` line errors with 
```
ERROR: MethodError: Cannot `convert` an object of type Float64 to an object of type MixedStructTypes.Uninitialized

Closest candidates are:
  convert(::Type{T}, ::T) where T
   @ Base Base.jl:84

Stacktrace:
 [1] MultiSchelling{…}(id::Int64, pos::Tuple{…}, mood::MixedStructTypes.Uninitialized, group::Int64, influence::Float64, type#226::Symbol)
   @ Main C:\Users\datse\.julia\packages\MixedStructTypes\U6UR1\src\CompactStructTypes.jl:51
 [2] Governor(; id::Int64, pos::Tuple{Int64, Int64}, group::Int64, influence::Float64)
   @ Main C:\Users\datse\.julia\packages\MixedStructTypes\U6UR1\src\CompactStructTypes.jl:104
 [3] top-level scope
   @ c:\Users\datse\.julia\dev\Agents\docs\src\tutorial.jl:737
Some type information was truncated. Use `show(err)` to see complete types.

```

it is because I did `{X}` in the super type but `{X<:Real}` in the subtype.

### LINKED ISSUE #968: Subtyping type parameterization does not work in `@multiagent`.
MWE:
```julia
using Agents


@multiagent struct MultiSchelling{X<:Real}(GridAgent{2})
    @agent struct Civilian # can't re-define existing `Schelling` name
        mood::Bool = false
        group::Int
    end
    @agent struct Governor{X<:Real} # can't redefine existing `Politician` name
        group::Int
        influence::X
    end
end
```

erros with 
```
ERROR: TypeError: in <:, expected Type, got a value of type TypeVar
Stacktrace:
 [1] top-level scope
   @ C:\Users\datse\.julia\dev\Agents\src\core\agents.jl:312
```

By the way, I find it odd that one must specify the type `X` in both the super type and the subtype. Can't the subtypes remain just a pure name ?

### PR DESCRIPTION
**Pull request by Tortar**
Fixes #968
Fixes #967 

I slightly changed the syntax in that package, and also solved some issues with the macros

### CODE REVIEW

**Comment by Tortar** [comment]
If I can kindly ask you George, can you give me your opinion on the syntax of https://github.com/JuliaDynamics/MixedStructTypes.jl? Do you think it is okay? :-)

**Comment by Tortar** [comment]
mmh actually again an instance of https://github.com/JuliaDynamics/Agents.jl/issues/963

**Comment by Datseris** [comment]
Hi @Tortar I am available today. I Can review. But this still seems to be WIP, right? What would you like me to review from MixedStructTypes.jl?

**Comment by Tortar** [comment]
It should be ready for review now actually

**Comment by Datseris** [comment]
right, so what's the status now? what's the syntax, if it changed?

**Comment by Tortar** [comment]
No I mean no changes still to the syntax, will do that in a separate PR, I meant to say that the syntax changed in MixedStructTypes.jl and so I adjusted the macro to the new one

**Comment by Datseris** [comment]
Right. but what is the syntax change? It is not obvious to me by just looking at the readme.

**Comment by Tortar** [comment]
From e.g. :

```julia
@sum_struct_type @kwdef A{X} <: AbstractA{X} begin
           mutable struct B{X}
               a::Tuple{X, X} = (1,1)
               b::Tuple{Float64, Float64} = (1.0, 1.0)
           end
           mutable struct C
               a::Tuple{Int, Int} = (2,2)
               d::Int32 = Int32(2)
           end
           mutable struct D
               a::Tuple{Int, Int} = (3,3)
               const c::Symbol = :s
           end
           struct E{X}
               a::Tuple{X, X} = (3,3)
           end
       end
```

to:

```julia
@sum_structs A{X} <: AbstractA{X} begin
           @kwdef mutable struct B{X}
               a::Tuple{X, X} = (1,1)
               b::Tuple{Float64, Float64} = (1.0, 1.0)
           end
           @kwdef mutable struct C
               a::Tuple{Int, Int} = (2,2)
               d::Int32 = Int32(2)
           end
           @kwdef mutable struct D
               a::Tuple{Int, Int} = (3,3)
               const c::Symbol = :s
           end
           @kwdef struct E{X}
               a::Tuple{X, X} = (3,3)
           end
       end
```

In practice a shorter name for the macro and a finer control on kwdef

**Comment by Datseris** [comment]
right, but how is its application Agents.jl? do the subagents start with `@subagent` or not anymore? I guess its better if they don't? (I also find odd the usage of `@kwdef` . can you remove it?)

**Comment by Tortar** [comment]
No changes to the Agents.jl syntax were made, I haven't applied the new syntax `@subagent`, etc..., I will do it in another PR, so I think this PR is good to go as it is

**Review by Datseris — APPROVED** [review]

**Pull request merged**
