### PR TITLE
Remove ismultiagenttype checks

### PR DESCRIPTION
**Pull request by Tortar**
Not needed anymore since we are abandoning the previous methodology for multiagent systems

### CODE REVIEW

**Review by Datseris — APPROVED** [review]

**Comment by Datseris** [comment]
op, all test sfail?

**Comment by Tortar** [comment]
now it works

**Comment by Tortar** [comment]
we could release 6.2 I think

**Comment by Datseris** [comment]
Right, should we mention anything more in the changelog? like "removed all references to the obsolete 'kind' concept, now everything is based on different agent types".

**Pull request merged**
