### PR TITLE
Fix bug due to last commit

### PR DESCRIPTION
**Pull request by Tortar**

### CODE REVIEW

**Comment by Tortar** [comment]
This passes tests locally, so it is safe to assume it does also here, if you want we can wait to see if this is the case for extra-safety @Datseris

**Comment by Tortar** [comment]
Not all tests actually, still need some changes, I assumed it was very easy

**Comment by Tortar** [comment]
Ok now everything really works locally

**Comment by Tortar** [comment]
now failings are the usual suspects :D

**Review by Datseris — APPROVED** [review]

**Pull request merged**
