### PR TITLE
Battle Royale example

### PR DESCRIPTION
**Pull request by Libbum**
In an attempt to investigate the discussion in #314, I've come up with this example. It runs, but I'm not completely happy with the output. (I'll need to add in a colour and marker legend before merging too, but that's less relevant than below)

I'll use *space* and *category* to separate the different dimensions of our `GridSpace`.

In no particular order:
- Cannot use AgentsPlots. It thinks we're a 3D plot. There would need to be some way to send it the spatial dimensions only.
- Periodic boundaries make no sense in a category, but would be nice to have in space.
    I wanted to have PBC's in this example initially, but when I have a level 2 agent and are looking for 'weaker' opponents, I'd like to return agents of level 1, not level 1, 10, 9, 8.
- Cannot decouple space and category.
    If I want to search for any agent with my level, I have to search ALL space, plus my current level. (100, 100, 1). This functionality really only works efficiently when we can completely decouple the categories.
- Cannot search for "larger than" or "less than" etc.
    All we have is neighbors in a radius, so in this specific example when I want to find "weak" or "strong", I have to find "weak" AND "strong", then filter one out.
- Lots of excess filtering in general. You can see through the example. Would be nice to consider if these are considered fine, or if  there is a way to make this better.
- Is there a strong motivation to do this vs agent properties?
    For really large grids, with the above things fixed, then yeah - maybe. But for the moment we're running through 100x100 grid spaces to find worthy agents, vs 50 total agents which could have a `level` property. 

As I suggested in #356, making `GridSpace` aware of categorical dimensions might be a way forward. But, take a look at the code here, and see if you can't find any better solutions, and we can adjust the example accordingly.

### CODE REVIEW

**Comment by Libbum** [comment]
battle

**Comment by Libbum** [comment]
The recent updates to the example and addition of #360 leaves my original list of issues with only one open point: cannot use AgentsPlots. I think this is completely fine, at least for the moment though. This is simply an example, and we do not have full support for such things, nor know if users will truly embrace the concept.

**Comment by Datseris** [comment]
My plan for AgentsPlots is to _kill it_ and use `InteractiveChaos` directly. I've changed interactive chaos and it now has only abstract plotting as a dependency. It already has all the code for the plots. The only thing remaining is to add a function for static plots, that doesn't do all the fancy animating.

**Comment by Libbum** [comment]
Sounds like a plan!

I'm having some issues getting the docs to build, but this will be ready once they pass.

**Comment by Datseris** [comment]
go ahead with merging from my perspective

**Pull request merged**
