### PR TITLE
Better functional termination of model run

### PR DESCRIPTION
**Pull request by Datseris**
This PR addresses #163 , by improving the API of `step!`.

It allows `when` to be just `true` (i.e. collect at every step). 

As I was coding this, I realized it is extremely important to have a fail safe mechanism. Some way to terminate evolution even if `n` doesn't give true.

This is done by the keyword `Nmax`.

But now @kavir1698 you really have to help me here. The source code inside `data_collector.jl`is a nightmare to deal with:

* No keyword propagation technique was used whatsoever, making the code base unmaintainable (I just wanted to add a new keyword, and now all hell broke loose... :D ) . To fix this I started using keyword propagation in step!, but we need much more.
* arguments are in entirely arbitrary order, completely incinsistent with `step!`, which has `n` before `properties`
* the `_step!` functions have crazy syntax. All keyword arguments are given as arguments, and then `df` is given.... Time to put all keyword arguments of `step!` to also be keyword arguments of `_step!`.

This is all so confusing. Can you please re-write this part of the code?

### CODE REVIEW

**Comment by kavir1698** [comment]
> Can you please re-write this part of the code?

It could take a bit for me to get to focus on this. But yeah.

**Comment by Libbum** [comment]
@kavir1698 I'd be up for assisting on this if need be.

**Comment by Datseris** [comment]
Sure, go ahead, but I think it is a hard task. I don't do it because I don't have too much familiarity with the data collector, and don't want to get a head-ache getting all methods correct, but if you want to put the effort, sure, go ahead!

**Comment by kavir1698** [comment]
Hi @Libbum , yes that would great. It might be a few days before I can start working on this.

**Comment by Datseris** [comment]
Closing in favor of #191

**Pull request closed without merging**
