### PR TITLE
removed `::Int` so that `paramscan` take `n::Function`

### PR DESCRIPTION
**Pull request by saumil-sh**
This PR addresses https://github.com/JuliaDynamics/Agents.jl/issues/706

### CODE REVIEW

**Comment by Datseris** [comment]
awesome!

- add a test that catches this
- increment patch version (3rd number) in project toml

**Comment by saumil-sh** [comment]
Is there a way to run a specific `testset` instead of running tests for the entire package?

**Comment by saumil-sh** [comment]
@Datseris, I am done here :) 
You can review it.

**Comment by AayushSabharwal** [comment]
> Is there a way to run a specific testset instead of running tests for the entire package?

I typically just comment out parts of `runtests.jl`. If you find a better way, please ping me :)

**Comment by fbanning** [comment]
> Is there a way to run a specific `testset` instead of running tests for the entire package?

Not that I know of.

> You can review it.

Looks good to me. Thanks for the PR.

**Review by fbanning — APPROVED** [review]

**Pull request merged**
