### PR TITLE
Agents 4.0 release 

### PR DESCRIPTION
**Pull request by Datseris**
Add release message and other changelogs.

Tim, perhaps it is worth considering to add the paper comparison table as is (screenshoted) to the ABM framework comparison? I'll add a link to it as well in the same page once I have uploaded it to a public achive.

### CODE REVIEW

**Comment by Libbum** [comment]
Sure. I'll see what needs to be done on the benchmarks first.

I just did the force prune operation that we did in #329, so re-dev and pull the repo again. Cleared out all of the excess previews. The new GH action should keep on top of new ones.

**Comment by Libbum** [comment]
@Datseris, I'm having a real hard time getting AgentsPlots to build against this PR. Got any pointers on how this can be fixed?

**Comment by Libbum** [comment]
With the update now in master, I can confirm that benchmarks are still relevant, no other reversions.

**Comment by Datseris** [comment]
what the hell is going on with AgentsPlots, why is version 0.3 tried to be installed instead of 0.4. How did you register it Tim?

```
    └─AgentsPlots [7820620d] log:
     ├─possible versions are: [0.1.0-0.1.2, 0.2.0-0.2.1, 0.3.0] or uninstalled
```

**Comment by Libbum** [comment]
With the [register](https://github.com/JuliaDynamics/AgentsPlots.jl/commit/09740cf5be404bdc6b8811a3591019a0bdd154b0#commitcomment-46329035) trigger.

**Comment by Libbum** [comment]
The CI calls build without issue locally, so I'll merge the master here and try again.

**Comment by Libbum** [comment]
OK, so I think I know whats happening now. We need AgentsPlots to be capable of using 4, so we add it to compat. But since v4 is not yet tagged, we go to the next possible AgentsPlots release, which is in the 0.3 category.  0.3 is not compatible with Agents v4, so we can't build docs with it. And we chase our own tail.

Suggestion: Tag 4.0.0, with docs not enabled at all. We'll have useless docs, but as soon as it's tagged, we release 4.0.1 with doc builds.

**Comment by Datseris** [comment]
okay I'll merge and tag in a bit

**Comment by Datseris** [comment]
@Libbum https://github.com/JuliaRegistries/General/pull/28630 is tagged, but I've lost the thread regarding the plotting stuff. Can you tag a 4.0.1 that plots? I'm preparing the announcement

**Comment by Libbum** [comment]
I was eating dinner, unsure if it was ready, but yep - I'll try to get a 4.0.1 working.

**Pull request merged**
