### PR TITLE
Logo for Agents 3.0

### LINKED ISSUE #160: New logo for version 3.0
I must admit that for months now I was displeased with the agents logo we came up, because it paid too much attention to cellular automata... which does injustice to Agents.

Now, with the new continuous space, we have an opportunity that I want to take.

@kavir1698 if you can get the social distancing model up to speed with the current state of the repo even without #155 I can take it from here.

The continuous space has stabilized a bit, besides #155 , and we can have this example in the docs already.

### PR DESCRIPTION
**Pull request by Datseris**
I've only modified Tim's code to not load a saved picture but use a font directly instead.

Closes #160

### CODE REVIEW

**Comment by Datseris** [comment]
This is what we have now: if we are all happy with it, I can put it up:

https://gph.is/g/Ev1jXN5

I have thought a lot about the font... I decided to go with Moon 2, it has a nice round quality.

**Comment by Libbum** [comment]
I've been playing around a little too.

Filesize is a little large. We can drop to 25 frames & `step!(..., 2)` without missing too much action.

```julia
plot!(p1; background_color = :transparent)
```
Will get you a transparent output for each `anim` frame - although the `gif` function doesn't handle that properly. You can build the gif yourself with

```
ffmpeg -framerate 25 -i %06d.png -i palette.bmp -lavfi paletteuse=alpha_threshold=128 -gifflags -offsetting agents.gif
```
although I doubt that's worth the trouble.

Finally, something I haven't finished with:
When we turn the axis off, scatter doesn't return just the data, it returns the place where the axes should be as well, just blank. Thus, the image doesn't scale to 100% our logo dimensions. Will post a solution to that once I've fiddled with `scatter` a bit.

**Comment by Datseris** [comment]
File size is irrelevant, all animations are hosted in JuliaDynamics's website repo and just linked to the docs!

**Comment by Libbum** [comment]
It's a hack, but this will get the job done:
```julia
scatter(rand(50,2), size = (1000,350), showaxis=false, right_margin=-2mm, top_margin=-2mm, bottom_margin=-5mm, left_margin=-11.5mm)
```

**Comment by Datseris** [comment]
what is `mm` ? its not defined for me.

**Comment by Libbum** [comment]
`using Measures`

-----Original Message-----

**Comment by Libbum** [comment]
https://gifyu.com/image/lMqz

**Comment by Datseris** [comment]
Is this animation with the parameters currently in the file?

**Comment by Libbum** [comment]
Yep, I didn't change anything other than the margin fix. 

Since we sample and have random start positions, some runs look better than others, but I didn't change any parameters for this one.

**Pull request merged**
