### PR TITLE
Schelling app, fix docs and test suite

### PR DESCRIPTION
**Pull request by Datseris**
The dev docs don't display the Daisyworld app video I've added in a recent PR. Better fix this in this PR. I'll monitor the Travis build...

### CODE REVIEW

**Comment by Datseris** [comment]
Oh yeah, some tests fail on 1.5 because of the changed RNG HAHA! Gotta fix that too!

**Comment by Datseris** [comment]
Oh man, these there are A LOT of failures... this is gonna need some effort.

**Comment by Libbum** [comment]
Don't alter the tests! We can use [StableRNGs](https://github.com/rfourquet/StableRNGs.jl) for our seeds and it should be fine to keep them as-is.

**Comment by Libbum** [comment]
Getting all tests to pass here will Close #247. #271 has been closed in favour of this.

**Comment by Datseris** [comment]
> I suggest a rewrite of the paramscan section with something a little less complex, like the example model already in collect_tests. Sound OK?

Yes, I actually also was wondering why we would have an entire forest fore definition file. Notice that we now have a `Models` module, we should have to define _any_ model in the tests.

> Scheduler tests are going to be complicated - many are testing the random activation portion of the scheduler, along-side the order of operations that currently depends on a seed. This could be one place that StableRNGs is useful?

**Comment by Datseris** [comment]
Alright, I've made many things deterministic. Tests pass locally for me, let's see what happens online. I've changed the `interaction_tests.jl` file, but I am wondering. Do we need it? Isn't everything that it tests already tested in `api_tests.jl` ? @Libbum I don't remember what you told me during the video call :D

**Comment by Libbum** [comment]
We can drop interaction_tests since it isn't really useful for us, but the paramscan testset in collect_tests need to be adapted. Currently they are commented out.

**Comment by Datseris** [comment]
Uuuuh, why do we have test failings with 
```
Expression: aggname(x_position, length) == "length_x_position"

   Evaluated: "length_getfield(Main, Symbol(\"#x_position#120\"))()" == "length_x_position"
```

**Comment by Datseris** [comment]
It was already announced that 1.6 will be the next LTS version of Julia and 1.0 is dropped. Shall we just drop the 1.0 tests already?

**Comment by kavir1698** [comment]
> It was already announced that 1.6 will be the next LTS version of Julia and 1.0 is dropped. Shall we just drop the 1.0 tests already?

Yes!

**Comment by Libbum** [comment]
aggname already has a [1.0 specific override](https://github.com/JuliaDynamics/Agents.jl/blob/245744702254ae9c9dfe8a54aee58f9786e750b3/src/simulations/collect.jl#L198). Weird that the behaviour has changed again???

If we drop 1.0 testing we can also drop this static guard.

**Comment by Datseris** [comment]
Okay but then we should make the julia dependency of Agents.jl to be 1.5 and bump version to 3.4. Also, Why do we use `join([string(agg), string(k)], "_")` instead of just `string(agg)*"_"*string(k)`...?

**Comment by Libbum** [comment]
Don't think there was any particular reason, just semantics. I would be a legacy remnant from when we used `mean(test)` and such with more complex joins. Your suggestion is about 3x faster, so it's a better solution now.

**Pull request merged**
