### PR TITLE
New syntax for aggname

### LINKED ISSUE #234: Discussion of naming convention for collected data
I was wondering whether it would be possible or desired to use `function_variable` rather than `function(variable)` as the naming convention of creating variables for data collection. For example, in the sheep wolf example:

```
adata = [(sheep, count), (wolves, count), (grass, count)]
results, _ = run!(model, agent_step!, n_steps; adata = adata)

pyplot()
@df results plot(:step, cols(Symbol("count(sheep)")), grid=false, xlabel="Step",
    ylabel="Population", label="Sheep")
```
it is necessary to wrap the variables around two functions. Furthermore, indexing columns is cumbersome. As far as I can tell, its not possible to index by `df.function_variable`.

### PR DESCRIPTION
**Pull request by Libbum**
Closes #234 by swapping `mean(weight)` to `:mean_weight` syntax.

### CODE REVIEW

**Comment by Datseris** [comment]
I forgot about this... remind me why we are doing this again? :D

**Comment by Libbum** [comment]
The nail in the coffin (for you) was `dataframe.mean_weight` is possible, but `dataframe.Symbol(...)` or `dataframe.aggname(..)` is not.

**Comment by Datseris** [comment]
God damn it , `mean(weight)` is so much more beautiful. Goes to show our world is "real" because we can't have perfection.

**Comment by Libbum** [comment]
> Besides, you can always `rename!` as you wish.

:P 

Agreed though. `mean(weight)` is nicer, but runs into practicality issues.

**Pull request merged**
