### PR TITLE
Further clarify mandatory API `ABM`

### LINKED ISSUE #899: Declare explicitly ABM Interface and deprecate calling `ABM` in favor of `StandardABM`
To make the creation of new models seamless we need to think well the Interface `ABM` should define. This interface should be **the minimal set of functions** that a subtype of `AgentBasedModel` should define, so that it satisfies out of the box **all of the API functions of Agents.jl** (such as `move_agent!`, etc.).

We have this mostly in place already. I jsut want to go through it a couple of times, while I am designing #759 . So I am assigning this to myself.

While doing this, we shiould also deprecate calling `ABM` directly in favor of `StandardABM`.

### PR DESCRIPTION
**Pull request by Datseris**
In preparation for the new Gillespie model, this PR closes #899 . 

I've also removed the agent type as a type parameter of the abstract `AgentBasedModel`, in foresight of future multi-agent models not being parameterized by a Union type. This change took me 2 hours to do.

### CODE REVIEW

**Comment by Datseris** [comment]
This is very frustrating. The tests of the IO are failing everywhere. This is really annoying that this part of the code is so hardcoded and doesn't use API functions.

**Comment by Datseris** [comment]
Okay I hope to get some help here. We have only two failures. One is for sure with the change @Tortar did with the ID iterator. I get:

```
sample!: Error During Test at C:\Users\gd419\.julia\dev\Agents\test\randomness_tests.jl:19
  Got exception outside of a @test
  MethodError: no method matching keys(::Base.ValueIterator{Dict{Int64, Agent1}})

  Closest candidates are:
    keys(::Union{Tables.AbstractColumns, Tables.AbstractRow})
     @ Tables C:\Users\gd419\.julia\packages\Tables\u1X7W\src\Tables.jl:189
    keys(::DataStructures.Trie)
     @ DataStructures C:\Users\gd419\.julia\packages\DataStructures\MKv4P\src\trie.jl:82
    keys(::DataStructures.Trie, ::AbstractString)
     @ DataStructures C:\Users\gd419\.julia\packages\DataStructures\MKv4P\src\trie.jl:82
    ...

  Stacktrace:
    [1] (::var"#159#172"{Base.ValueIterator{Dict{Int64, Agent1}}, StandardABM{GridSpace{2,
typeof(dummystep), typeof(dummystep), typeof(Agents.Schedulers.fastest), Nothing, StableRNf::Symbol)
      @ Main .\none:0
    [2] iterate
Agents.Schedulers.fastest), Nothing, StableRNGs.LehmerRNG}}}})
      @ Base .\array.jl:707
    [8] macro expansion
      @ C:\Users\gd419\.julia\dev\Agents\test\randomness_tests.jl:29 [inlined]
    [9] macro expansion
      @ C:\Users\gd419\.julia\juliaup\julia-1.9.1+0.x64.w64.mingw32\share\julia\stdlib\v1.9\Test\src\Test.jl:1498 [inlined]
   [10] top-level scope
      @ C:\Users\gd419\.julia\dev\Agents\test\randomness_tests.jl:20
   [11] include(fname::String)
      @ Base.MainInclude .\client.jl:478
   [12] macro expansion
      @ C:\Users\gd419\.julia\dev\Agents\test\runtests.jl:153 [inlined]
   [13] macro expansion
      @ C:\Users\gd419\.julia\juliaup\julia-1.9.1+0.x64.w64.mingw32\share\julia\stdlib\v1.9\Test\src\Test.jl:1498 [inlined]
   [14] top-level scope
      @ C:\Users\gd419\.julia\dev\Agents\test\runtests.jl:151
   [15] include(fname::String)
      @ Base.MainInclude .\client.jl:478
   [16] top-level scope
      @ none:6
   [17] eval
      @ .\boot.jl:370 [inlined]
   [18] exec_options(opts::Base.JLOptions)
      @ Base .\client.jl:280
   [19] _start()
      @ Base .\client.jl:522
```

The other failure is related with the AgentsIO tests checking the internal `nextid` field. The tests fail because the generated model has nextid 0. I don't know why but maybe @AayushSabharwal can help:

```
ContinuousSpace: Test Failed at C:\Users\gd419\.julia\dev\Agents\test\jld2_tests.jl:9
  Expression: (getfield(model, :maxid)).x == (getfield(other, :maxid)).x
   Evaluated: 0 == 10

Stacktrace:
 [1] macro expansion
   @ C:\Users\gd419\.julia\juliaup\julia-1.9.1+0.x64.w64.mingw32\share\julia\stdlib\v1.9\Test\src\Test.jl:478 [inlined]
 [2] (::var"#test_model_data#572")(model::UnremovableABM{ContinuousSpace{2, true, Float64, 
typeof(Agents.no_vel_update)}, Bird, typeof(flocking_model_agent_step!), typeof(dummystep), Agents.Schedulers.Randomly, Nothing, StableRNGs.LehmerRNG}, other::StandardABM{ContinuousSpace{2, true, Float64, typeof(Agents.no_vel_update)}, Bird, typeof(dummystep), typeof(dummystep), Agents.Schedulers.Randomly, Nothing, StableRNGs.LehmerRNG})
   @ Main C:\Users\gd419\.julia\dev\Agents\test\jld2_tests.jl:9
GridSpace: Test Failed at C:\Users\gd419\.julia\dev\Agents\test\jld2_tests.jl:9
  Expression: (getfield(model, :maxid)).x == (getfield(other, :maxid)).x       
   Evaluated: 0 == 30

Stacktrace:
 [1] macro expansion
   @ C:\Users\gd419\.julia\juliaup\julia-1.9.1+0.x64.w64.mingw32\share\julia\stdlib\v1.9\Test\src\Test.jl:478 [inlined]
 [2] (::var"#test_model_data#572")(model::UnremovableABM{GridSpace{2, false}, SchellingAgent, typeof(schelling_model_agent_step!), typeof(dummystep), Agents.Schedulers.Randomly, Dict{Symbol, Int64}, StableRNGs.LehmerRNG}, other::StandardABM{GridSpace{2, false}, SchellingAgent, typeof(dummystep), typeof(dummystep), Agents.Schedulers.Randomly, Dict{Symbol, Int64}, StableRNGs.LehmerRNG})
   @ Main C:\Users\gd419\.julia\dev\Agents\test\jld2_tests.jl:9
```


Other than these 2 failures, this PR is good to go.

**Comment by Tortar** [comment]
will take a look at the failures and review the PR soon!

**Comment by AayushSabharwal** [comment]
The second test failure (`:maxid` not matching) is because loading a model from a file always creates a `StandardABM`, which increments `maxid` as agents are added. However, the model that was serialized initially is an `UnremovableABM`, which does not use `maxid`

**Comment by Datseris** [comment]
@AayushSabharwal what's the fix?

**Comment by AayushSabharwal** [comment]
I'll have to experiment with it and see. Shouldn't be too hard

**Comment by Tortar** [comment]
I'm solving both of the problems @AayushSabharwal, thanks for bisecting the cause (saying this so that we don't do the double of the work)

**Review by Tortar — APPROVED** [review]

**Pull request merged**
