### PR TITLE
Changing type order in `ABM`

### LINKED ISSUE #364: Change Type parameterization order for ::ABM, make `Space` first
It is almost exclusively the case that we dispatch on the _second_ type parameter of `ABM`, the space type. Perhaps it makes sense to make this type first in the type paraterization, so we no longer have to write `::ABM{A, GridSpace} where {A<:AbstractAgent}`, but simply `::ABM{GridSpace}` ?

Besides the fact that we have to do this change throughout the source, is there any downside? The simplification upside is huge I believe.

### PR DESCRIPTION
**Pull request by Libbum**
Closes #364

First pass at this. Tests run, although there may be some questions as to how daisyworld runs - will see how documentation builds.

Think I covered all of the needed changes. Unsure how much of an improvement this makes are though...

### CODE REVIEW

**Comment by Libbum** [comment]
Right.. We'll need to patch AgentsPlots for this to work...

**Comment by Datseris** [comment]
Yeah haven't really realized how often we were using `A` inside functions. Thankfully this definitely simplifies many docstrings, where now the `{A, ` is no longer necessary.

For agents plots we can simply make the docs use master branch again by doing `Pkg.add("AgentsPlots#master")` in the `make.jl`, and make a quick update on the plots repo

**Comment by Datseris** [comment]
i will spend some time trying out cairo makie anyways for our docs

**Comment by Libbum** [comment]
Examples all look good!

**Comment by Datseris** [comment]
So this is good to merge right? Anything missing? If not, go ahead.

**Comment by Libbum** [comment]
Yep. Good for someone else to take a glance at it, just in case.

**Pull request merged**
