### PR TITLE
Updated sugarscape

### PR DESCRIPTION
**Pull request by AayushSabharwal**
Uses the new plotting code so that the heatmap and agents plot are in the same video

### CODE REVIEW

**Comment by Libbum** [comment]
Yep, that looks good! I'll merge it in a second. Waiting on some CI results.

**Comment by AayushSabharwal** [comment]
I realised the plots don't have titles. I'll add them in a minute

**Comment by AayushSabharwal** [comment]
I'm sorry, something urgent came up. Can this PR wait a bit?

**Comment by Libbum** [comment]
Sure, not a problem.

**Comment by Libbum** [comment]
@AayushSabharwal Happy with this now?

**Comment by AayushSabharwal** [comment]
Yeah. I should've mentioned it

**Pull request merged**
