### PR TITLE
Filtering for random_nearby_*

### PR DESCRIPTION
**Pull request by Tortar**
This implements the filtering feature discussed in #650, in the process I created two new function `sampling_with_condition_single` and `sampling_with_condition_agents_single` so that to reuse the code. Some benchmarks using the code posted in #650 seem good:

```julia
julia> @btime random_nearby_id($(25,25), model, 10) setup=(model=periodic_model())
  171.405 μs (17884 allocations: 845.36 KiB)
54290

julia> f(x, y) = true
f (generic function with 1 method)

julia> @btime random_nearby_id($(25,25), model, 10, f) setup=(model=periodic_model())
  242.911 μs (17893 allocations: 1.14 MiB)
66712

julia> f(x, y) = false
f (generic function with 1 method)

julia> @btime random_nearby_id($(25,25), model, 10, f) setup=(model=periodic_model())
  354.953 μs (17893 allocations: 1.14 MiB)
```

But this PR still needs some tests for the new functionality, which I will implement soon --> test added

### CODE REVIEW

**Comment by Tortar** [comment]
I implemented `sampling_with_condition_agents_single` so that we can use the filter also on `random_nearby_agent`, the cool thing is that we could use this function also in `random_agent`, but here I made the choice to require two arguments for the filter i.e. the element (`pos, id, agent`) and the `model` so that this method is not fully compatible with random_agent which instead requires only to pass the agent, I think that passing the element and the model will be better in terms of flexibility so we could break the current code for this new one, what do you think?

**Comment by Datseris** [comment]
Changing the behavior of the `nearby_agent` is breaking, so we can't do that. besides, I'd argue we should also have the 1-argument version here as well. One can always create an anonymous closure
```
# inside `agent_step!`
f = a -> two_arg_version(a, model)
random_nearby...
```

**Comment by Tortar** [comment]
I agree with you, everything should be ok now! 
Anyway Happy Easter!

**Review by Datseris — APPROVED** [review]
happy easter to you too! Thanks for the fantastic contributions! please bump minor version, add changelog, merge and tag!

**Pull request merged**
