### PR TITLE
Output svgs to file first

### PR DESCRIPTION
**Pull request by Libbum**
Following on from [discussions about DOM poisioning](https://discourse.julialang.org/t/cairomakie-and-fontconfig/55931?u=libbum), this PR will try to figure out the best way to solve that issue.

### CODE REVIEW

**Comment by Datseris** [comment]
why do you save svg instead of `png`?

**Comment by Libbum** [comment]
Doesn't really matter. We're fixing an svg issue, so..

If this 'fixes' the issue we can use either. Julius has opened an issue on Documenter to fix the problem we have at present.

**Comment by Libbum** [comment]
I think this has been recently solved in the latest Documenter.jl. Will need to test.

**Comment by Libbum** [comment]
Closing, as #467 solves this problem.

**Pull request closed without merging**
