### PR TITLE
Simpler ABM print

### PR DESCRIPTION
**Pull request by kavir1698**
Here is a small suggestion to avoid long and unhelpful ABM printing.

### CODE REVIEW

**Comment by Datseris** [comment]
Is it correct to say that if properties is e.g.:
```julia
Base.@kwdef struct P
a = 1
b = 2
c = 3
end
```
then in this PR the values of the fields of `P` will **not** be shown when printing the model?

Can you provide an example where this is PR results in more helpful behavior?

**Comment by kavir1698** [comment]
> then in this PR the values of the fields of `P` will **not** be shown when printing the model?
>
> Can you provide an example where this is PR results in more helpful behavior?

Yes, the values will not be shown. Unless `properties` has short scaler values, the print become bloated. I personally find that behavior annoying.

**Comment by Libbum** [comment]
Yeah, I agree with your sentiment @kavir1698. Printing properties is only somewhat helpful if you have a small model, anything else and its a mess.

I'd even go so far as to remove the property print all together since users can always do `model.properties` directly if they need a list.

Thoughts on just dropping this all together? Or maybe just having `property count: $(length(model.properties))`?

**Comment by Datseris** [comment]
I prefer the current approach where at least the property names are given.

**Comment by kavir1698** [comment]
> Thoughts on just dropping this all together? Or maybe just having `property count: $(length(model.properties))`?

I have never had too many property names. I also feel printing their names doesn't hurt.

**Review by Datseris — APPROVED** [review]

**Comment by Datseris** [comment]
Actually, I'd suggest to print the properties each in an individual line. What do you think about that? (current printing is also like this, as it prints like a dictionary)

**Comment by kavir1698** [comment]
> Actually, I'd suggest to print the properties each in an individual line. What do you think about that? (current printing is also like this, as it prints like a dictionary)

Currently, a list of descriptions for `space` prints in a single line and it is clean. The names of `properties` in a single line sounds good to me.

**Comment by Libbum** [comment]
Per line I don't like, it's going to be the same issue that we had in the first place: too much noise. I like Ali's recent change, it works well.

**Comment by Datseris** [comment]
Okay from me.

**Comment by Libbum** [comment]
We'll release this patch when the new JLD2 implementation is completely ready.

**Pull request merged**
