### PR TITLE
Two convenience syntaxes for getting model propertries and agents

### LINKED ISSUE #166: Feature request: propagate model.symbol to model.properties[:symbol]
For `:symbol` not already in model fields. 

(I have done this before in DynamicalBilliards.jl, I will try it here in a PR as well)

### PR DESCRIPTION
**Pull request by Datseris**
This PR introduces two syntaxes that I find much beetter than what we have now:

1. `model[id]` gives the agent with `id`, i.e. it is `model.agents[id]`.
2. `model.property` gives the entry of `model.properties`. For example, `model.β` gives `model.properties[:β]`.

Motivation: I was extremely displeased about how super verbose it is to get model properties. I was also displeased that getting the agent with `id` is so complicated, given that the dictionary is central and should be more easy to do that. 

This PR resolves everything. It deprecates the function `id2agent` which is useless now.

Closes #166 .

### CODE REVIEW

**Comment by Datseris** [comment]
TODO: replace all `model.properties[:whatever]` with `model.whatever` in the docs.

**Comment by Datseris** [comment]
@Libbum I altered some text, but the tests fail. I've tried to correct them. What did I do wrong...?

**Comment by Datseris** [comment]
@Libbum I have done your hotfixes here already.

**Comment by Libbum** [comment]
Test is failing because the warning text is not updated on line 63 in `api_tests.jl`.

Don't have time to do a proper review tonight, but the changes look great. This really makes life easier. I'll take a deeper look tomorrow.

**Comment by itsdfish** [comment]
Will the conditional return type introduce additional type instability? 
```
function Base.getproperty(m::AgentBasedModel, s::Symbol)
    if s ∈ (:agents, :space, :scheduler, :properties)
        return Base.getfield(m, s)
    else
        return Base.getindex(m.properties, s)
    end
end
```


```
julia> @code_warntype model.x
Variables
  #self#::Core.Compiler.Const(getproperty, false)
  m::AgentBasedModel{Shopper,Agents.GraphSpace{SimpleDiGraph{Int64}},typeof(fastest),Dict{Symbol,Any}}
  s::Symbol

Body::Any
1 ─ %1 = (:agents, :space, :scheduler, :properties)::Core.Compiler.Const((:agents, :space, :scheduler, :properties), false)
│   %2 = (s ∈ %1)::Bool
└──      goto #3 if not %2
2 ─ %4 = Base.getfield::Core.Compiler.Const(getfield, false)
│   %5 = (%4)(m, s)::Union{typeof(fastest), Agents.GraphSpace{SimpleDiGraph{Int64}}, Dict}
└──      return %5
3 ─ %7 = Base.getindex::Core.Compiler.Const(getindex, false)
│   %8 = Base.getproperty(m, :properties)::Any
│   %9 = (%7)(%8, s)::Any
└──      return %9
```

```
@code_warntype model.properties[:x]
Variables
  #self#::Core.Compiler.Const(getindex, false)
  h::Dict{Symbol,Any}
  key::Symbol
  val::Union{}
  index::Int64

Body::Any
1 ─       Core.NewvarNode(:(val))
│         (index = Base.ht_keyindex(h, key))
│         $(Expr(:inbounds, true))
│   %4  = (index < 0)::Bool
└──       goto #3 if not %4
2 ─ %6  = Base.KeyError(key)::KeyError
│         Base.throw(%6)
└──       Core.Compiler.Const(:(return %7), false)
3 ┄ %9  = Base.getproperty(h, :vals)::Array{Any,1}
│   %10 = Base.getindex(%9, index)::Any
│   %11 = Core.typeassert(%10, $(Expr(:static_parameter, 2)))::Any
└──       return %11
4 ─       $(Expr(:inbounds, :pop))
└──       Core.Compiler.Const(:(return val), false)
```

As a point of reference, here is a case in which properties is a struct rather than a dictionary:

```
@code_warntype model.properties.stock
Variables
  #self#::Core.Compiler.Const(getproperty, false)
  x::Store
  f::Symbol

Body::Int64
1 ─ %1 = Base.getfield(x, f)::Int64
└──      return %1
```

**Comment by Datseris** [comment]
Thanks for pointing this out @itsdfish ! I've opened a question about this: https://discourse.julialang.org/t/overloading-getproperty-in-a-type-stable-manner/36638

The way I have done this before, was to use only `getproperty` and `getfield`. Now I am mixing things and type instability occurs. 

If it is not possible to get rid of type instability, I will obviously remove this change (but change `model[id]` remains, and is type stable as well).

**Comment by Datseris** [comment]
Thanks for pointing this out @itsdfish ! I've opened a question about this: https://discourse.julialang.org/t/overloading-getproperty-in-a-type-stable-manner/36638

The way I have done this before, was to use only `getproperty` and `getfield`. Now I am mixing things and type instability occurs. 

If it is not possible to get rid of type instability, I will obviously remove this change (but change `model[id]` remains, and is type stable as well).

**Comment by itsdfish** [comment]
No problem. I'm glad that I can help a bit.

I've encountered a similar problem before. In many cases, multiple dispatch can be used as an alternative to an if statement, but that looks unlikely in this case. Parameters.jl has a macro that unpacks all fields of a struct (maybe a dictionary could work too), but it is described as "somewhat dangerous" (last paragraph https://mauro3.github.io/Parameters.jl/stable/manual/). It would be nice if there is a better way to access nested content. The best workaround I know of to limit verbosity is to use an alias at the beginning of a function , such as p = model.properties.

**Comment by Datseris** [comment]
Alright, I've resolved this. The new method _is indeed type stable_. Notice that this type stability can only exist within functions not in global scope (otherwise no constant propagation can happen).

But, by definition, nothing is type stable in global scope so we can't even care about the instability in global scope.

**Comment by Datseris** [comment]
> but that looks unlikely in this case

Not really, I have done this before for another package, but here it was only a hair more tricky. Anyway, it works now exactly as originally intended :)

**Comment by itsdfish** [comment]
I'm glad you figured out something. The solution seems a little weird to me. I'm still trying wrap my head around it. The changes you made also have the benefit of working on structs as well as dictionaries. Nice!

**Pull request merged**
