### PR TITLE
GR nul test

### PR DESCRIPTION
**Pull request by Libbum**
Ref #437. Our build times are around 35-40 minutes on docs at the moment.. Lets see how this fairs out of curiosity.

### CODE REVIEW

**Comment by Datseris** [comment]
Just installing Conda and matplotlib takes 10 minutes... Is this because of open street map?

**Comment by Datseris** [comment]
Actually I'm confused now. Where does matplotlib and conda even come from? I thought open street map was Plots.jl...?

**Comment by Libbum** [comment]
Yes, its OSM. `pyplot` backend.

**Comment by Libbum** [comment]
Oh, and we also needed it for things like Wolf Sheep transparent markers. That's no longer an issue though, so we can probably drop pyplot completely in #435.

**Comment by Libbum** [comment]
That made exactly zero change.

**Pull request closed without merging**
