### PR TITLE
clean up grid space

### PR DESCRIPTION
**Pull request by Datseris**
unfortunately even though I ported most code from TimeseriesPrediction.jl, we can't use it due to design. We still use a lot of stuff though.

### CODE REVIEW

**Comment by Datseris** [comment]
also add `has_empty_nodes` which I have forgotten.

**Comment by Libbum** [comment]
`get_node_agents` is also missing (that was the one I should have added, but actually added the space_neighbor function yesterday)

**Comment by Libbum** [comment]
I didn't absorb too much of that `inner` was doing, are we loosing performance by removing it, or just not gaining something additional since it doesn't work in this context?

**Comment by Datseris** [comment]
I turned out not using it because it made us lose performance by using it. It's a bit complicated to explain why and since we ditch it I'll not go into details ... :P

**Comment by Datseris** [comment]
`get_node_agents` is just `(mode[id] for id in get_node_contents(pos, model))`, right?

**Comment by Datseris** [comment]
I don't know whether we should have it, or if we should, then we should also have same version for `space_neighbors`, that returns an agent iterator instead of id iterator...?

**Comment by Libbum** [comment]
That's it yeah. We added it from user feedback if I recall, but I don't think it really needs to be around. We use it in three examples where it doesn't truly need to be there. I wouldn't go complicating space_neighbors anymore at the moment. Let's do #301, which will need a documentation overhaul too, see if it really needs to remain.

**Pull request merged**
