### PR TITLE
Warn only once

### PR DESCRIPTION
**Pull request by Tortar**

### CODE REVIEW

**Comment by Tortar** [comment]
Actually this still have some problems

**Comment by Datseris** [comment]
Why warn only once? I would argue we should warn all the time to make sure people get it and update their code. If they don't want to update their code they shouldn't use agetns.jl v6.

**Comment by Tortar** [comment]
This warns once in a session, but in all sessions it will restate the warning, it is a bit too annoying that you are flood with the same warning hundreds of times

**Review by Datseris — APPROVED** [review]

**Comment by Datseris** [comment]
fine. i prefer to flood people and make them update the code but that is not a popular approach.

**Pull request merged**
