### PR TITLE
Small improvement in sampling_with_condition_single function

### PR DESCRIPTION
**Pull request by Tortar**
A small improvement in execution time

```julia
julia> f(x) = false
f (generic function with 1 method)

julia> @benchmark random_nearby_id($(25,25), model, 10, f) setup=(model=periodic_model()) #new
BenchmarkTools.Trial: 387 samples with 1 evaluation.
 Range (min … max):  305.611 μs …   4.827 ms  ┊ GC (min … max): 0.00% … 91.75%
 Time  (median):     332.832 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   350.827 μs ± 229.440 μs  ┊ GC (mean ± σ):  3.26% ±  4.66%

julia> @benchmark random_nearby_id($(25,25), model, 10, f) setup=(model=periodic_model()) #current
BenchmarkTools.Trial: 382 samples with 1 evaluation.
 Range (min … max):  346.306 μs …   4.814 ms  ┊ GC (min … max): 0.00% … 90.59%
 Time  (median):     413.123 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   454.338 μs ± 388.431 μs  ┊ GC (mean ± σ):  7.49% ±  8.04%
```

Not much, but I think worth it :-)

Also improved some testing

### CODE REVIEW

**Comment by Tortar** [comment]
I have actually thought about some further optimizations, hopefully the last ones :D but I need some time to figure out how to organize the code for applying them

**Comment by Tortar** [comment]
experimenting seems that there is not much more to gain, so I think this is the final form of this PR

**Comment by Tortar** [comment]
I'm thinking that maybe we could parallelize some of these algorithms in the future, this should be possible without any restriction for the user

**Review by Datseris — APPROVED** [review]

**Comment by Datseris** [comment]
Parallelizing thinsg would be nice

**Pull request merged**
