### PR TITLE
Elementary cellular automata example

### PR DESCRIPTION
**Pull request by astenuz**
Hi! I wanted to add this simple example to the library. Its the elementary cellular automata described here https://mathworld.wolfram.com/ElementaryCellularAutomaton.html

Also, maybe to improve it, how would you approach making a video of the process. It would be nice to have a video of the model adding row by row until it forms the final picture.

This is an example with rule 30
image

### CODE REVIEW

**Comment by Datseris** [comment]
Hi there, thanks for the PR! In the example library we already have the game of life example. Does this one bring any new useful information to the list of examples? What I'm thinking is that the examples are becoming a lot, but not all may be useful. So as an alternative I'm thinking of opening a new repo, AgentsExamplesZoo.jl, which will host _any_ example anyone would like to contribute, and would have no real limitation on the amount of examples.

(The only reason this is a problem for this repo is because it increases the amount of time of the CI)

@Libbum

**Comment by astenuz** [comment]
That sounds good, It could also allow to have each example on its own folder/workspace in case it requires different libraries or something like that.

**Comment by Libbum** [comment]
Yeah. So I've got a few research level pieces of work that I'd like to include in the Agents.jl documentation in a more curated fashion, but it's clear that our example section is growing beyond being helpful and moreso becoming an issue to manage.

I like the idea of an `Agents.jl Example Zoo`, which we can accept user submissions, maybe even build only specific doc pages on merge. This can integrate with the current documentation, but certainly be more free form and less curated by the developers.

**Comment by Libbum** [comment]
Let's get moving on this repo first:
- AgentsExamplesZoo.jl
- Agents.jl_Example_Zoo
Any other naming suggestions for it?

**Comment by Datseris** [comment]
AgentsExamplesZoo.jl is the way for me!

**Comment by Libbum** [comment]
Why do we need the .jl for this though? Is this not a documentation repository - a compendium of models, but not a library / package within itself.

**Comment by Datseris** [comment]
My thinking is that it is run via Documenter and produces its own doc pages that shows all examples being run.

**Comment by Libbum** [comment]
I think running on documenter is for sure the way to go. Don't think it needs .JL to work. Guess we can play around with the repo name before publishing regardless

**Comment by Datseris** [comment]
@astenuz thank you! In Agents.jl 5.0 all examples besides the 5 central ones to the library will be in a new repository called "Agents.jl Example Zoo". Can you please make this PR there instead? https://github.com/JuliaDynamics/Agents.jl_Example_Zoo

(please close this when you open the new PR)

**Comment by Datseris** [comment]
I'm closing this now, feel free to move it to AgentsExampleZoo.jl if you are interested to contribute.

**Pull request closed without merging**
