### PR TITLE
Minor OSM fixes

### PR DESCRIPTION
**Pull request by AayushSabharwal**
Waiting for docs to build to see how this looks

### CODE REVIEW

**Comment by AayushSabharwal** [comment]
Hmm I wonder if we can re-export the docstring somehow

**Comment by Datseris** [comment]
? Just put `OSM.download_osm_network` in the `@docs` block?

**Comment by AayushSabharwal** [comment]
> ? Just put OSM.download_osm_network in the @docs block?

I did. It reports the docstring as missing.

**Comment by Datseris** [comment]
Ah sorry sorry, in the `makedocs` function in make.jl you need to add the LightOSM module in the `modules` argument.

**Comment by Datseris** [comment]
@AayushSabharwal sorry for yet again annoying you with the Goettingen map, but can we please get the pedestrian version? :) :) The version we have now seems like the car-oriented version, and I really hate cars :) 

image


(there are no "roads" in the city center)

**Comment by AayushSabharwal** [comment]
image

This looks better.

**Comment by AayushSabharwal** [comment]
There's a minor annoyance with this: it requires downloading with `network_type = :none`. As a result, using this map requires `network_type = :none` to be passed into the `OSMSpace` constructor (for `graph_from_file`) otherwise the extra edges are simply filtered out. I'll add this to the docstring for `OSM.test_map`.

**Comment by Datseris** [comment]
Do you plot this without errors...?

**Comment by AayushSabharwal** [comment]
Nope, same error. It still plots, though.

**Comment by AayushSabharwal** [comment]
It's nice that doc builds take minutes now instead of an hour

**Comment by AayushSabharwal** [comment]
That's just...absurd. Why is windows downloading the old map?

**Comment by Datseris** [comment]
yeah for me it also downloaded the wrong map :P

**Comment by AayushSabharwal** [comment]
Could you please try deleting the contents of `Artifacts.toml` and downloading?

**Comment by AayushSabharwal** [comment]
All tests pass for me on windows.

**Comment by AayushSabharwal** [comment]
Is there some sort of caching going on behind the scenes for windows? I'm at a bit of a loss, because I can't replicate this locally.

**Pull request merged**
