### PR TITLE
Add keyword support for agent_add! 

### PR DESCRIPTION
**Pull request by itsdfish**
Attempt 2 of https://github.com/JuliaDynamics/Agents.jl/pull/184

### CODE REVIEW

**Comment by Datseris** [comment]
I've fixed the missing ABM, but making the tests pass is now on you (there is an invalid redefinition of Agent2 in the tests , that I don't know where you use your Agent2 and where you use our Agent2).

In any case after tests pass I will review in detail.

**Comment by itsdfish** [comment]
Sorry about that. I didn't realize the Agent types were defined in the runtests file. One thing that might be useful is https://github.com/YingboMa/SafeTestsets.jl, which ensures that each test is isolated from the variables of others.

I fixed the problem by adding Agent7. However, I encountered a new error online 66 of api_tests.jl:

```
    @test_logs (:warn, "Agent struct should be a concrete type. If your agent is parametrically typed, you're probably seeing this warning because you gave `Agent` instead of `Agent{Float64}` (for example) to this function. You can also create an instance of your agent and pass it to this function.") ABM(ParametricAgent, GridSpace((1,1)))

```
Error
```
Log Test Failed at /home/dfish/.julia/dev/Agents/test/api_tests.jl:66
  Expression: ABM(ParametricAgent, GridSpace((1, 1)))
  Log Pattern: (:warn, "Agent struct should be a concrete type. If your agent is parametrically typed, you're probably seeing this warning because you gave `Agent` instead of `Agent{Float64}` (for example) to this function. You can also create an instance of your agent and pass it to this function.")
  Captured Logs: 
    Test.LogRecord(Warn, "Agent struct should be a concrete type. If your agent is parametrically typed, you're probably seeing this warning because you gave `Agent` instead of `Agent{Float64}` (for example) to this function. You can also create an instance of your agent and pass it to this function. If you want to use `Union` types, you can silence this warning.", Agents, :model, :Agents_d3ff3562, "/home/dfish/.julia/dev/Agents/src/core/model.jl", 122, Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}())
```

I'm not sure how to fix it. Do you know how to?

**Comment by itsdfish** [comment]
Thanks for fixing the previous issue. I fixed a few other bugs, but ran into a few more that I am not sure how to resolve.

1) In api_tests.jl, "move_agent!" is broken on line 192. This appears to be a preexisting problem. 

2) I changed Space to GridSpace on line 169 of api_tests.jl according to the deprecation message. However, on line 172 `add_agent!(1, model, attributes...)` there is an error indicating incorrect functionality. I am basing the example on the SIR in the dev version of the docs. That doesn't work there either. I'm not sure what configuration is required.

**Comment by Datseris** [comment]
Sorry for all these broken tests. All of them are in fact fixed in PR #182 , they were remnants of a stupid merge on my end, that didn't properly test checks. I'll take care of the remaining errors.

**Comment by itsdfish** [comment]
No problem. It happens. Thanks for your help!

**Comment by Datseris** [comment]
We are currently in the process of developing Agents 3.0, and we can't make other releases on 2.0 before that, so this will take a while to be in a stable version.

**Comment by itsdfish** [comment]
Thanks for keeping me informed. I look forward to 3.0. By chance, do you maintain any sort of roadmap somewhere?

**Comment by Datseris** [comment]
https://github.com/JuliaDynamics/Agents.jl/projects/2  feel free to contribute we definitely need the help!

**Pull request merged**
