### PR TITLE
Update examples to v6.0

### LINKED ISSUE #898: Update examples into v6
Following https://github.com/JuliaDynamics/Agents.jl/pull/889  we need to update all other examples. This change is trivial and it simply means: remove passing `agent_step!` to `step!/run!/abmplot!` and instead give these functions to the model constructor.

### PR DESCRIPTION
**Pull request by Tortar**
Fixes #898

### CODE REVIEW

**Comment by Tortar** [comment]
ok, seems that even if all examples run locally, they don't run on the docs since we need to first define the stepping functions since code is run in blocks in the docs

**Comment by Tortar** [comment]
Actually, it was simpler than that, just move the call to initialization after the stepping definition. PR should be good to go now

**Review by Datseris — APPROVED** [review]

**Comment by Datseris** [comment]
I haven' checked at the docs yet. If all videos are produced fine, then merge!

**Comment by Tortar** [comment]
Seem fine to me 👍

**Pull request merged**
