### PR TITLE
Create `uniform_randomwalk!`

### PR DESCRIPTION
**Pull request by Tortar**
This is a new function to support generic N-dimensional isotropic random walks, mentioned as interesting to have in #799 .

I benchmarked the new function against the old one with

<details> <summary>benchmark </summary>

```julia
using Agents, Random, BenchmarkTools

@agent A ContinuousAgent{2} begin end
@agent B ContinuousAgent{3} begin end

function cont_model_2d(; numagents = 1000, dims = (20, 20))
           space = ContinuousSpace(dims, periodic = false)
           rng = MersenneTwister(23)
           model = ABM(A, space; rng = rng)
           for _ in 1:numagents
               add_agent!(A, model, (1,1))
           end
           return model
       end

function cont_model_3d(; numagents = 1000, dims = (20, 20, 20))
           space = ContinuousSpace(dims, periodic = false)
           rng = MersenneTwister(23)
           model = ABM(B, space; rng = rng)
           for _ in 1:numagents
               add_agent!(B, model, (1,1,1))
           end
           return model
       end

model_2d = cont_model_2d()
model_3d = cont_model_3d()

agent_2d = model_2d[1]
agent_3d = model_3d[1]

@benchmark randomwalk!($agent_2d, $model_2d, 1)
@benchmark randomwalk!($agent_3d, $model_3d, 1)
@benchmark uniform_randomwalk!($agent_2d, $model_2d, 1)
@benchmark uniform_randomwalk!($agent_3d, $model_3d, 1)
```
</details>

which shows some notable improvements (the greatest part of the time is now in the last call of `walk!`): 

```julia
julia> @benchmark randomwalk!($agent_2d, $model_2d, 1)
BenchmarkTools.Trial: 10000 samples with 956 evaluations.
 Range (min … max):  91.632 ns … 835.669 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     94.874 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   96.353 ns ±  14.382 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

   ▃▆█▇▄▂                                                      ▂
  ▇██████▇▄▄▅▃▄▁▁▄▅▅▅▅▆▄▅▆▅▅▆▄▅▃▅▅▆▆▆▅▄▃▄▆▁▄▅▄▄▄▄▅▇▅▄▅▃▄▅▄▄▃▃▆ █
  91.6 ns       Histogram: log(frequency) by time       143 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.

julia> @benchmark randomwalk!($agent_3d, $model_3d, 1)
BenchmarkTools.Trial: 10000 samples with 855 evaluations.
 Range (min … max):  142.807 ns … 947.602 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     147.251 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   149.270 ns ±  18.042 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

   ▃▆██▆▃▁                                                      ▂
  ▆███████▅▄▄▁▄▄▄▄▄▅▇▇▇▆▆▆▆▄▄▃▄▆▆▅▅▃▁▁▁▁▃▃▄▆▆▆▆▆▅▃▅▅▄▄▄▄▆▅▅▅▆▄▄ █
  143 ns        Histogram: log(frequency) by time        209 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.

julia> @benchmark uniform_randomwalk!($agent_2d, $model_2d, 1)
BenchmarkTools.Trial: 10000 samples with 976 evaluations.
 Range (min … max):  82.480 ns … 724.693 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     86.373 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   87.304 ns ±   9.864 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

      ▂█▁
  ▂▂▂▄███▃▂▂▂▂▁▂▁▁▂▂▂▂▂▂▂▂▂▂▁▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▂▂▂▂▁▂▂▂▂▂▂ ▂
  82.5 ns         Histogram: frequency by time          124 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.

julia> @benchmark uniform_randomwalk!($agent_3d, $model_3d, 1)
BenchmarkTools.Trial: 10000 samples with 966 evaluations.
 Range (min … max):  84.886 ns … 734.576 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     89.027 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   90.114 ns ±  10.239 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

      ▂█▅
  ▂▂▃▅███▇▃▂▂▂▂▂▂▁▂▂▂▂▂▂▂▂▁▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▂▂▂▂▂▂▂▂▂▂▂ ▂
  84.9 ns         Histogram: frequency by time          127 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.
```

this version is also generic, it supports any number of dimensions.

I didn't choose to extend `randomwalk!` since it was not so easy to differentiate between the different functions via multiple dispatch due to the fact that we use polar and azimuthal as `kargs` currently. So that not to complicate the code much more, I chose to create a new function. If we make those kargs normal args then it will be easier to use multiple dispatch, but I'm fine also with the current version, let me know what you think. 

It still needs tests, but I want to know what is the opinion on all of this

### CODE REVIEW

**Comment by Datseris** [comment]
I think I'm a bit lost: isn't isotropic/uniform walks what happens by default in `randomwalk!`...?

**Comment by Tortar** [comment]
yes, exactly, in practice I choose to do that since I found multiple dispatch in this particular case a bit difficult to deal with because we don't have enough args to differentiate between functions, but I'm willing to reformulate my approach to extend `randomwalk!` instead of creating a new function, if you have any suggestion on this front let know :-)

**Comment by Datseris** [comment]
let me think about it. it is almost certain that we don't need two function names. I'llcome back to #802

**Comment by Tortar** [comment]
Finally found a way through!! Everything works now

**Comment by Tortar** [comment]
merging with #802

**Pull request closed without merging**
