### PR TITLE
Pathfinding performance improvements 

### PR DESCRIPTION
**Pull request by AayushSabharwal**
Fixed dynamic dispatch on `delta_cost` call (`@code_typed` output indicates that `pathfinder.cost_metric` is concretely typed)

Working on reducing allocations in `find_path`.

### CODE REVIEW

**Comment by AayushSabharwal** [comment]
Improving performance is a more difficult task than I anticipated. I have managed to modify the algorithm so it allocates less, and it performs better than the current implementation on a simple `find_path` benchmark, but is also considerably worse when running a model with it.

Is it feasible to allocate an array `Int32` the same dimensions as the grid as part of the `AStar` struct? This be used to keep track of different connected components in the grid. This improves the worst case when no path can be found between two nodes because they are in different components and the entirety of one component ends up being searched.

**Comment by Libbum** [comment]
We haven't had too many people complaining about memory issues, so maybe that's OK. But it we're trading a few miliseconds for O(n^d) memory requirements then its probably not worth it. We'd want something a bit more significant.

**Comment by AayushSabharwal** [comment]
I think this is the best possible without preallocating.
Results on the `find_path` benchmark from the notebook:
Before:
```
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):  354.666 μs …   7.235 ms  ┊ GC (min … max): 0.00% … 89.73%
 Time  (median):     371.428 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   410.658 μs ± 318.680 μs  ┊ GC (mean ± σ):  5.20% ±  6.31%

  ▆█▇▇▆▅▄▄▄▄▄▃▃▃▂▂▁▁▁▁ ▁                                        ▂
  ████████████████████████▇█▇▇██▇█▇█▇▆▆▆▇▄▆▆▆▅▅▆▆▅▆▆▅▅▄▆▅▄▆▅▅▄▅ █
  355 μs        Histogram: log(frequency) by time        656 μs <

 Memory estimate: 350.66 KiB, allocs estimate: 1920.
```
After:
```
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):  351.363 μs …   5.017 ms  ┊ GC (min … max): 0.00% … 91.20%
 Time  (median):     358.365 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   384.443 μs ± 290.308 μs  ┊ GC (mean ± σ):  5.44% ±  6.59%

  ▄██▇▆▅▄▃▂▁▁▁    ▁▁▁▁▁                                         ▂
  ████████████▇▇█████████▆▃▆▄▆▆▆▅▅▅▅▄▄▅▄▄▄▅▆▅▆▁▅▁▃▃▅▁▄▃▄▃▃▄▄▃▃▄ █
  351 μs        Histogram: log(frequency) by time        509 μs <

 Memory estimate: 350.66 KiB, allocs estimate: 1920.
```
It's minor, but noticeable. It also improved runtime on a model by 0.2s over 10k steps.

**Comment by AayushSabharwal** [comment]
The new ordering for the `PriorityQueue` uses the h-cost as a tiebreaker when f-cost is identical, thus searching nodes closer to the target first in case of a tie. This leads to significant improvements when there aren't many obstacles in the way.

**Comment by Libbum** [comment]
> This leads to significant improvements when there aren't many obstacles in the way.

Can you show an example of this? The benchmarks you show above don't show too much difference - but maybe they're not looking at this case?

In principle the code for this PR looks good though.

**Comment by AayushSabharwal** [comment]
Sure, I'll write a benchmark for this

**Comment by AayushSabharwal** [comment]
I benchmarked `find_path` from `(1, 1)` to `(1000, 1000)` on a pathfinder with `trues(1000, 1000)` as the `walkmap`.

Interestingly, it seems like this reduces the nodes explored (judging by the lower memory estimate) but takes more time on average. I'm not sure why this is the case.
Before:
```
BenchmarkTools.Trial: 2344 samples with 1 evaluation.
 Range (min … max):  1.949 ms …   5.269 ms  ┊ GC (min … max): 0.00% … 57.50%
 Time  (median):     1.985 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   2.128 ms ± 548.100 μs  ┊ GC (mean ± σ):  5.49% ± 11.51%

  █▆▅▃                                                     ▁   
  █████▇▆▇▇▇▅▅▄▅▁▁▃▁▃▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁██▇ █
  1.95 ms      Histogram: log(frequency) by time      4.59 ms <

 Memory estimate: 3.68 MiB, allocs estimate: 13100.
```
After:
```
BenchmarkTools.Trial: 1950 samples with 1 evaluation.
 Range (min … max):  2.420 ms …   5.131 ms  ┊ GC (min … max): 0.00% … 43.91%
 Time  (median):     2.452 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   2.559 ms ± 437.571 μs  ┊ GC (mean ± σ):  3.24% ±  8.86%

  █▆▄▁▁                                                     ▁  
  █████▇▅▇▇▆▃▆▅▅▅▄▃▁▃▁▁▁▃▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▄██ █
  2.42 ms      Histogram: log(frequency) by time      4.75 ms <

 Memory estimate: 2.76 MiB, allocs estimate: 13061.
```

**Comment by AayushSabharwal** [comment]
I have been using [this article](https://theory.stanford.edu/~amitp/GameProgramming/Heuristics.html) as a reference, specifically the section on breaking ties.

**Comment by AayushSabharwal** [comment]
This handles a simple edge case when `from` or `to` are out of bounds/unwalkable and instantly exits instead of exploring the entire map.

**Comment by AayushSabharwal** [comment]
One single test fails occasionally when changes are made to the algorithm, since it takes the other one of two equivalent paths. I modified the check so either path passes.

**Comment by Libbum** [comment]
So the modifications here are getting a little confusing. Since you swapped this from a draft I guess I'm now questioning if that implies what's here at the moment is close to merge ready. But longer times on average seems like a path that we don't want to go down?

**Comment by AayushSabharwal** [comment]
I should clarify:
I removed the tiebreaker using the h-cost, so the "Before" benchmark is our current status. I also handled an edge case, where if the starting or ending positions are invalid (out-of-bounds or unwalkable) it exists straight away, instead of going through the entire grid as it did before.

**Comment by Libbum** [comment]
OK, no worries. So does that mean you're happy for us to take a closer look at the code at this point and things are merge ready in your view?

**Comment by AayushSabharwal** [comment]
Yes!

**Review by Libbum — APPROVED** [review]
Finally had a chance to look over the edge case stuff - all looks good.

**Comment by AayushSabharwal** [comment]
Can I merge this, then?

**Comment by AayushSabharwal** [comment]
Bumped patch version before I forget to. Is this good to go now?

**Comment by Datseris** [comment]
yes, go ahead, and also tag a realese!

**Pull request merged**
